feat: ajout du composant follow (nous suivre) [DS-801][DS-805]
GouvernementFR/dsfr pull request #10
Opened 2021-06-16 14:10 UTC by keryanS

2021-06-28 17:50 UTC, lab9fr requested changes

2021-06-28 17:50 UTC, lab9fr commented on src/follow/example/samples/socials-newsletter-highlight.ejs
> +      url: "https://www.facebook.com/gouvernement.fr",
contentPlaceholder

2021-06-28 17:50 UTC, lab9fr commented on src/follow/example/samples/socials-newsletter-highlight.ejs
> +<%
Créer le socials un peu plus bas, en sous section séparée pour éviter de l'avoir dans plusieurs fichiers différents en mode copier coller

2021-06-28 17:50 UTC, lab9fr commented on src/follow/example/samples/socials-only.ejs
> +
la même que précédemmment, à mutualiser les différents fichiers, on se fait un point dessus si tu veux.

2021-06-28 17:50 UTC, lab9fr commented on src/follow/styles/_module.scss
> +      @include margin-right(12.5%);
pour retirer une colonne ?

2021-06-28 17:50 UTC, lab9fr commented on src/follow/styles/_module.scss
> +    @include nest-link(md, only, facebook-circle-fill, null, false);
vu qu'ils sont déjà nesté en links ligne 89, à tester de mettre tout null sauf l'icon, ça devrait alléger la css.
si ça ne marche pas, tester avec 
@include before {
    @include icon-content(xxx);
}

2021-06-28 17:50 UTC, lab9fr commented on src/follow/styles/_settings.scss
> +/// Buttons Settings
normalement, tu utilises des rf-links, tu n'as pas besoin de setting là

2021-06-28 17:50 UTC, lab9fr commented on src/follow/templates/ejs/follow.ejs
> +# paramètres search-bar
follow

2021-06-28 17:50 UTC, lab9fr commented on src/follow/templates/ejs/follow.ejs
> +      <div class="<%= prefix %>-grid-row <%= prefix %>-grid-row--gutters">
dans les 2 cas t'as grid-row gutter, tu peux déjà clarifier en les sortant des if

2021-06-28 17:50 UTC, lab9fr commented on src/follow/templates/ejs/follow.ejs
> +      <div class="<%= prefix %>-grid-row <%= prefix %>-grid-row--gutters">
et tu peux simplifier les tests : 

```
if (newsletter) {
let gclasses = [col-12]
if (socials) gclass + = col-md-8
<div includeClasses(gclass) >
include(newsletter)
</div>
}
if (socials) {
let gclasses = [col-12]
if (newsletter) gclass + = col-md-4
<div includeClasses(gclass) >
include(social)
</div>
}
```

2021-06-28 17:50 UTC, lab9fr commented on src/follow/templates/ejs/socials.ejs
> +        <%- include('../../../links/templates/ejs/link', { place: "only", attributes: {title: "xxxxxxxx - ouvre une nouvelle fenêtre"}, href: networks[i].url, blank: true, label: networks[i].label, c
t'as pas besoin de mettre en only normalement

2021-06-28 17:50 UTC, lab9fr commented on src/inputs/styles/_module.scss
> +  > *:not(:last-child) {
manque un first-child au cas où on arrive par la suite à 3 éléments

2021-06-29 14:05 UTC, keryanS commented on src/follow/styles/_module.scss
> +      @include margin-right(12.5%);
C'est l'espacement entre le bloc de droite et le séparateur, qui correspond a 1/8 soit 1 colonne du md-8

2021-06-29 14:39 UTC, keryanS commented on src/follow/example/samples/socials-newsletter-form.ejs
> +      url: "https://www.facebook.com/gouvernement.fr",
A priori ils auront pas a modifier les liens puisque j'ai mis les vrai liens, avec href="[À MODIFIER | https://www.youtube.com/gouvernementfr]" c'est moins plug and play

2021-06-29 14:59 UTC, keryanS commented on src/follow/example/samples/socials-newsletter-highlight.ejs
> +<%
j'ai fais un fichier data.ejs que je json.parse dans chaque sample comme pour les forms, c'est ce à quoi tu pensais ?

2021-06-29 15:02 UTC, keryanS commented on src/follow/styles/_module.scss
> +    @include nest-link(md, only, facebook-circle-fill, null, false);
@include nest-link(md, only, null, null, true, true);
Le fait de mettre null au param icon fait qu'on ajoute pas la fonticon sur le before. Donc le @include icon-content(xxx); suffit pas.

2021-06-29 15:10 UTC, keryanS commented on src/follow/example/samples/socials-newsletter-form.ejs
> +      url: "https://www.facebook.com/gouvernement.fr",
<a class="fr-link--facebook fr-link" title="xxxxxxxx - ouvre une nouvelle fenêtre" href="[À MODIFIER | https://www.facebook.com/gouvernement.fr]" target="_blank">facebook</a>  ???

2021-06-30 11:14 UTC, lab9fr approved these changes

2021-07-08 10:00 UTC, lab9fr requested changes

2021-07-08 10:00 UTC, lab9fr commented on src/follow/styles/_module.scss
> +      height: 100%;
mixin

2021-07-08 10:01 UTC, lab9fr requested changes

2021-07-08 10:01 UTC, lab9fr commented on src/follow/styles/_module.scss
> +            max-width: 50%;
mixin

2021-07-08 17:10 UTC, keryanS commented
Changer le lien vers la doc (actuellement celui de footer)

2021-07-09 15:33 UTC, lab9fr approved these changes

2021-07-09 16:00 UTC, merged