🐛 feat(sidemenu): correction focus sidemenu sticky [DS-3842]
GouvernementFR/dsfr pull request #1008
Opened 2024-09-18 08:28 UTC by zellerbaptiste

- corrige le focus croppé sur la variante de navigation latérale sticky

2024-10-09 15:43 UTC, keryanS requested changes
<img width="1497" alt="image" src="https://github.com/user-attachments/assets/f4a76e64-4a27-484b-96ee-f56a54366b5b">

--- 

<img width="509" alt="image" src="https://github.com/user-attachments/assets/f46c2e39-70e0-4f1c-8eb3-85fde01c9abb">

2024-10-11 09:31 UTC, zellerbaptiste commented
> <img alt="image" width="1497" src="https://private-user-images.githubusercontent.com/2979634/375030768-f4a76e64-4a27-484b-96ee-f56a54366b5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MzgzODksIm5iZiI6MTcyODYzODA4OSwicGF0aCI6Ii8yOTc5NjM0LzM3NTAzMDc2OC1mNGE3NmU2NC00YTI3LTQ4NGItOTZlZS1mNTZhNTQzNjZiNWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTFUMDkxNDQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTIzYzE1YTBjODEyNWQyNDA4YjY1M2U4Y2JjODc2ZjA0MjBkZDFkOWEzNWYwZmQ2ZTYyOTBjYThlOTNhYmQ1YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.P58r1QmCcG7JQKObf_0i8C98okqfIdsLwGmhsbBUtTY">
> <img alt="image" width="509" src="https://private-user-images.githubusercontent.com/2979634/375031143-f46c2e39-70e0-4f1c-8eb3-85fde01c9abb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MzgzODksIm5iZiI6MTcyODYzODA4OSwicGF0aCI6Ii8yOTc5NjM0LzM3NTAzMTE0My1mNDZjMmUzOS03MGUwLTRmMWMtOGViMy04NWZkZTAxYzlhYmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTFUMDkxNDQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTBmNjg0MjhmNDQ2ODI1NzVmNWVkZWY3YjRlODI4MDY4MDU2OGUyNTQxODNmOWFlNDVjNTVmMGYxMzk0NTllZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.awb5zo9aquc4RKA3xbqhwarm8GgXqI-9gLbuvxl-0sU">

La version sticky-full-height est corrigée.

Pour le mobile j'ai poussé un correctif qui pourrait être appliqué également sur le header et d'autres composant full-width qui ont ce soucis de focus croppé

2024-10-11 10:20 UTC, keryanS approved these changes

2024-10-22 10:24 UTC, lab9fr approved these changes

2024-10-23 15:13 UTC, merged