:bug: :boum: feat(table): correction de l'attribut aria-sort
GouvernementFR/dsfr pull request #1030
Opened 2024-10-16 09:31 UTC by zellerbaptiste

- remplace l'attribut `aria-sorting` par `aria-sort` sur les bouton de tri avec comme valeurs `descending` et `ascending` ( fix #1026 )
- met à jour la page d'exemple des tableaux

2024-10-16 09:35 UTC, keryanS requested changes

2024-10-16 09:35 UTC, keryanS commented on src/component/button/style/_legacy.scss
> +    @include animate.rotate('&[aria-sort='descending']');
Cette ligne est redondante sur IE je pense

2024-10-16 10:03 UTC, keryanS approved these changes

2024-10-23 09:14 UTC, lab9fr approved these changes

2024-10-23 15:55 UTC, merged