fix: bug legacy IE [DS-1088]
GouvernementFR/dsfr pull request #139
Opened 2021-11-17 17:01 UTC by keryanS

radios riche taille image
centrage icone seule

2021-11-18 17:02 UTC, lab9fr commented on src/core/style/function/_encoding.scss
> +  $svg: str-replace($svg, '"', '%22');
à checker, mais le remplacement des doubles quote par des simples quote semble suffire si l'ensemble de l'uri est comprise dans des doubles quotes

2021-11-18 17:02 UTC, lab9fr commented on src/core/style/function/_encoding.scss
> +  $svg: str-replace($svg, '/', '\/');
j'ai l'impression que ça n'est pas mis en place, non ?

2021-11-18 17:05 UTC, lab9fr requested changes

2021-11-18 17:05 UTC, lab9fr commented on src/core/style/function/_encoding.scss
>  @function svg-encode($svg) {
à rajouter un paramètre $legacy qui conditionne les replace que tu as rajouté

2021-11-18 17:12 UTC, keryanS commented on src/core/style/function/_encoding.scss
> +  $svg: str-replace($svg, '"', '%22');
exact

2021-11-18 17:12 UTC, keryanS commented on src/core/style/function/_encoding.scss
> +  $svg: str-replace($svg, '/', '\/');
exact inutile

2021-11-18 17:57 UTC, keryanS commented on src/core/style/function/_encoding.scss
>  @function svg-encode($svg) {
Ce qui demande de déplacer les appels dans scheme. 
On a pas conditionner l'import des css legacy donc dupliqué sur les exemples. @todo : ajouter un <!-- if IE --> ?

2021-11-19 15:28 UTC, lab9fr approved these changes

2021-11-19 15:29 UTC, merged