refactor: nettoyage et simplification du système de couleur [DS-2212]
GouvernementFR/dsfr pull request #160
Opened 2021-12-04 21:27 UTC by lab9fr

2021-12-06 15:14 UTC, zellerbaptiste commented on src/core/style/color/_function.scss
> -@import 'function/get-scheme-shade';
Joli nettoyage !

2021-12-06 16:43 UTC, zellerbaptiste approved these changes
Globalement l'utilisation des objets de configs aide à la refacto 👍  mais dans l'usage il est nécessaire de mettre à jour les commentaires des Mixins et d'ajouter des exemples d'utilisation pour la documentation.

2021-12-06 16:44 UTC, zellerbaptiste commented on src/component/accordion/main.scss
> +/* ¯¯¯¯¯¯¯¯¯ *\
💯

2021-12-07 11:43 UTC, keryanS requested changes

2021-12-07 11:43 UTC, keryanS commented on src/component/select/style/_scheme.scss
> +    @include scheme-element-data-uri-svg(text title grey, (legacy: $legacy), $select-arrow-down-svg);
<img width="866" alt="Capture d’écran 2021-12-07 à 12 21 47" src="https://user-images.githubusercontent.com/2979634/145020645-ed2cd681-a606-45c5-89e5-5532594ac772.png">

L'icone apparait maintenant sur IE,, on a deux icone avec celle native.
Ajouter en legacy : 
select::-ms-expand {
    display: none;
}

2021-12-07 12:07 UTC, keryanS approved these changes

2021-12-07 13:00 UTC, merged