feat(logo): modifie l'intitulé par défaut [DS-2249]
GouvernementFR/dsfr pull request #165
Opened 2021-12-10 16:00 UTC by zellerbaptiste

2021-12-17 19:14 UTC, lab9fr requested changes

2021-12-17 19:14 UTC, lab9fr commented on src/component/logo/template/ejs/logo.ejs
> +    <%- logo.title || 'Intitulé<br>officiel' %>
à mettre plutôt dans le sample, pas de contenu texte dans les templates, sauf s'il s'agit vraiment d'un intitulé définitif.

2021-12-17 19:14 UTC, lab9fr commented on src/component/header/template/ejs/brand.ejs
>                          path = '../../../logo/template/ejs/logo';
ce cas là ne devrait plus exister. si intitulé non défini, erreur.

2021-12-17 19:15 UTC, lab9fr requested changes
Dans la page d'exemple brand, les exemples sm et lg ont "République Française" au lieu d'"Intitulé Officiel"

2021-12-20 14:07 UTC, zellerbaptiste commented on src/component/logo/template/ejs/logo.ejs
> +    <%- logo.title || 'Intitulé<br>officiel' %>
done

2021-12-20 14:07 UTC, zellerbaptiste commented on src/component/header/template/ejs/brand.ejs
>                          path = '../../../logo/template/ejs/logo';
done

2022-01-10 10:59 UTC, lab9fr approved these changes

2022-01-10 11:00 UTC, merged