feat(icon): ajoute la nouvelle font-icon
GouvernementFR/dsfr pull request #168
Opened 2021-12-16 14:30 UTC by zellerbaptiste

2021-12-17 18:52 UTC, lab9fr requested changes
Il manque l'icon _blank pour les liens au fil du texte (sur la documentation sur dev)

2021-12-21 17:28 UTC, zellerbaptiste commented
> Il manque l'icon _blank pour les liens au fil du texte (sur la documentation sur dev)

c'est corrigé

2022-01-12 13:43 UTC, keryanS requested changes

2022-01-12 13:43 UTC, keryanS commented on src/component/callout/example/index.ejs
> +let icon = '-icon-info-line';
```suggestion
let icon = 'icon-info-line';
```

2022-01-12 13:43 UTC, keryanS commented on src/component/callout/template/ejs/callout.ejs
> + if (callout.icon !== undefined) classes.push(prefix + callout.icon);
```suggestion
 if (callout.icon !== undefined) classes.push(prefix + '-' + callout.icon);
```

2022-01-12 13:43 UTC, keryanS commented on src/core/style/icon/_tool.scss
> +          font-weight: 700;;
L'ancienne font est en 700 de graisse et la nouvelle en 400 ??

2022-01-12 13:52 UTC, zellerbaptiste commented on src/core/style/icon/_tool.scss
> +          font-weight: 700;;
exact !

2022-01-12 14:01 UTC, lab9fr approved these changes

2022-01-12 14:13 UTC, merged