fix(scheme): ajoute methode de detection du localstorage
GouvernementFR/dsfr pull request #170
Opened 2021-12-21 16:12 UTC by zellerbaptiste

2022-01-11 09:22 UTC, lab9fr commented
Structure

internals: {
	ns,
	register,
	preventManipulation,
	legacy: {
		isLegacy
		setLegacy
	},	
	dom: {
		addClass
		hasClass
		queryParentSelector
		querySelectorAllArray
		removeClass
	},
	support: {
		supportLocalStorage
	},
	property: {
		completeAssign
	}
	
}

on laisse mode, inspector exposé au global

attention '../../../core/script/api/utilities/propertie' => property

2022-01-11 13:01 UTC, zellerbaptiste commented
@lab9fr j'ai mis a jour le structure de l'api, prêt pour review.

2022-01-12 14:25 UTC, lab9fr requested changes

2022-01-12 14:25 UTC, lab9fr commented on src/core/script/api/internals.js
> +const internals = [];
pourquoi un array et pas un objet ?
```suggestion
const internals = {};
```

2022-01-12 14:25 UTC, lab9fr commented on src/core/script/api/internals.js
> +const legacy = [];
pareil
```suggestion
const legacy = {};
```

2022-01-12 14:25 UTC, lab9fr commented on src/core/script/api/register/instance.js
> +import api from '../../../api.js';
en fait, c'est mieux de ne pas avoir l'api à ce niveau pour laisser Instance en indépendant de l'élément api, vu qu'on ajoute par la suite Instance sur api via le core. Petit retour en arrière nécessaire je pense

2022-01-12 14:25 UTC, lab9fr commented on src/core/script/api/register/registration.js
> +import api from '../api.js';
même chose ici

2022-01-12 14:25 UTC, lab9fr commented on src/core/script/api/scroll/scroll-locker.js
> +import api from '../api.js';
pareil ici

2022-01-12 14:25 UTC, lab9fr commented on src/core/script/api/utilities/property/index.js
> +const property = [];
```suggestion
const property = {};
```

2022-01-12 14:25 UTC, lab9fr commented on src/core/script/api/utilities/support/index.js
> +const support = [];
```suggestion
const support = {};
```

2022-01-12 14:25 UTC, lab9fr commented on src/core/script/disclosure/disclosure.js
> +import api from '../../../api.js';
pareil, retour

2022-01-12 14:25 UTC, lab9fr commented on src/core/script/disclosure/disclosures-group.js
> +import api from '../../../api.js';
idem

2022-01-12 14:28 UTC, zellerbaptiste commented on src/core/script/api/internals.js
> +const internals = [];
yes c'est vrai ça, pourquoi ??
je corrige merci

2022-01-12 15:12 UTC, lab9fr approved these changes

2022-01-12 15:14 UTC, merged