fix(doc): met a jour la doc des templates ejs [DS-1787]
GouvernementFR/dsfr pull request #171
Opened 2021-12-23 11:17 UTC by zellerbaptiste

2021-12-23 13:18 UTC, zellerbaptiste commented
RAF : Doc du composant Header

2022-01-05 15:10 UTC, keryanS requested changes

2022-01-05 15:10 UTC, keryanS commented on src/component/tab/template/ejs/tabs.ejs
> +    ** tabs.viewportWidth (boolean, optional): option d'affichage dans la page d'exemples
SI true, défini la taille du composant en full width (sans marge en mobile)

2022-01-05 15:10 UTC, keryanS commented on src/component/tab/template/ejs/tabs.ejs
> +    ** tabs.attributes (object, required): attributs du composant
** tabs.attributes (object, **optional**): attributs du composant

2022-01-05 15:10 UTC, keryanS commented on src/component/tag/template/ejs/tag.ejs
> +* tag.size (string, optional) : taille du composant
- valeurs {default: md} : 
* sm : tag taille small

2022-01-06 10:22 UTC, zellerbaptiste commented on src/component/card/template/ejs/card.ejs
>  * card.img (string, optionnal) : url de l'image
je mets a jour le type de la donnée, dans cette template on ne passe que l'objet `card.img`

2022-01-06 10:24 UTC, zellerbaptiste commented on src/component/checkbox/template/ejs/checkbox-group.ejs
> -* checkbox.id (string, required): id du checkbox
il est passé en paramètre mais non utilisé dans cette template

2022-01-06 10:26 UTC, zellerbaptiste commented on src/component/checkbox/template/ejs/checkbox-group.ejs
> -* checkbox.label (string, optional): label du checkbox
il est passé en paramètre depuis l'index.ejs mais non utilisé dans cette template, je l'ai ajouté dans la template 'checkbox.ejs'

2022-01-06 10:40 UTC, zellerbaptiste commented on src/component/radio/template/ejs/radio.ejs
> +
ces attributs existent sur l'objet `radio.image` mais ne sont pas utiles dans cette template

2022-01-06 10:49 UTC, zellerbaptiste commented on src/component/footer/template/ejs/content.ejs
non justifié dans cette template il me semble

2022-01-07 15:23 UTC, keryanS commented on src/component/card/template/ejs/card.ejs
>  * card.img (string, optionnal) : url de l'image
En effet mais c'est bien un objet et non pas une string. 
card.img est un objet qui doit contenir un src et un alt, pas juste une string

2022-01-07 15:25 UTC, keryanS commented on src/component/checkbox/template/ejs/checkbox-group.ejs
> -* checkbox.id (string, required): id du checkbox
J'avais un doute sur ça, a certain endroit j'ai mis les paramètre uniquement la ou ils sont utilisés.
Mais ça demande aux utilisateurs d'aller voir dans les sous templates les paramètres à prévoir dans le parent, donc porte a confusion. Qu'en penses tu ?

2022-01-07 15:30 UTC, keryanS commented on src/component/footer/template/ejs/content.ejs
Je pensais au cas ou on aurait un label différent du lien réel.
Ou si le site est en http et pas https.
(hors scope de ce ticket, mais évol a prévoir a mon avis)

2022-01-07 15:34 UTC, keryanS requested changes
cf commentaires

2022-01-10 14:44 UTC, zellerbaptiste commented on src/component/card/template/ejs/card.ejs
>  * card.img (string, optionnal) : url de l'image
c'est corrigé pour `* card.img (object, optional) : paramètres de l'image`

2022-01-10 14:45 UTC, zellerbaptiste commented on src/component/checkbox/template/ejs/checkbox-group.ejs
> -* checkbox.id (string, required): id du checkbox
comme vu en point ce matin on reste sur le principe de n'ajouter la documentation que sur les variables utilisées dans la template

2022-01-10 14:45 UTC, zellerbaptiste commented on src/component/checkbox/template/ejs/checkbox-group.ejs
> -* checkbox.label (string, optional): label du checkbox
comme vu en point ce matin on reste sur le principe de n'ajouter la documentation que sur les variables utilisées dans la template

2022-01-11 11:31 UTC, keryanS requested changes

2022-01-11 11:31 UTC, keryanS commented on src/component/tag/template/ejs/tag.ejs
> +
il manque
* tag.tag (string, optional) : La balise utilisée pour le tag (default: a), si pas de href utiliser 'button'

2022-01-11 16:46 UTC, zellerbaptiste commented on src/component/tag/template/ejs/tag.ejs
> +
@keryanS je ne vois d'utilisation de `tag.tag` dans cette template ?

2022-01-14 18:28 UTC, lab9fr requested changes

2022-01-14 18:28 UTC, lab9fr commented on src/component/summary/template/ejs/list.ejs
>  	** summaryList.list (array, required) : Tableau de liens enfants (href, label)
mettre en forme array []

2022-01-21 15:03 UTC, zellerbaptiste commented on src/component/consent/template/ejs/manager.ejs
>  *   |- title (string, recommanded): titre de la finalité
c'est corrigé

2022-01-21 15:07 UTC, zellerbaptiste commented on src/component/summary/template/ejs/list.ejs
>  	** summaryList.list (array, required) : Tableau de liens enfants (href, label)
corrigé

2022-01-25 13:36 UTC, lab9fr requested changes

2022-01-25 13:36 UTC, lab9fr commented on src/component/footer/template/ejs/brand.ejs
>  * footer.operator (object, optional) : Paramètres du logo operator
operator devrait faire partie de brand, c'est le cas au niveau de la structure et dans le header

2022-01-25 13:36 UTC, lab9fr commented on src/component/footer/template/ejs/footer.ejs
> +* footer.operator (object, optional) : Paramètres du logo operator
si operator fait partie de brand, il n'apparait donc pas à ce niveau

2022-01-25 13:38 UTC, lab9fr commented
dans header et dans footer, on a footer qui est directement passé aux sous templates en lieu de chaque objet spécifique (brand devrait recevoir juste brand, etc) La doc se fait le reflet de cette incohérence. Faudrait qu'on corrige ça par la même occasion.

2022-01-27 18:17 UTC, lab9fr requested changes

2022-01-27 18:17 UTC, lab9fr commented on src/component/header/example/sample/header.ejs
> +                data.body.brand.service = { title: servicePlaceholder.title };
```suggestion
                brand.service = { title: servicePlaceholder.title };
```

2022-01-27 18:17 UTC, lab9fr commented on src/component/header/example/sample/header.ejs
> +    data.body.tools = {};
```suggestion
    const tools = {};
    data.body.tools = tools;
```

2022-01-27 18:17 UTC, lab9fr commented on src/component/header/example/sample/header.ejs
> +        data.body.tools.links = {
```suggestion
        tools.links = {
```

2022-01-27 18:17 UTC, lab9fr commented on src/component/header/example/sample/header.ejs
> +        data.body.tools.links = header.links;
```suggestion
        tools.links = header.links;
```

2022-01-27 18:17 UTC, lab9fr commented on src/component/header/example/sample/header.ejs
> +        data.body.tools.search = header.search === true ?
```suggestion
        tools.search = header.search === true ?
```

2022-01-27 18:17 UTC, lab9fr commented on src/component/header/example/sample/header.ejs
> +        data.body.tools.search.id = header.searchId || uniqueId('search');
```suggestion
        tools.search.id = header.searchId || uniqueId('search');
```

2022-01-27 18:17 UTC, lab9fr commented on src/component/header/example/sample/header.ejs
> +        data.body.tools.search.modalId = navbar.search.modalId;
```suggestion
        tools.search.modalId = navbar.search.modalId;
```

2022-01-27 18:17 UTC, lab9fr commented on src/component/header/example/sample/header.ejs
> +        data.body.tools.id = uniqueId('tools');
```suggestion
        tools.id = uniqueId('tools');
```

2022-01-27 18:17 UTC, lab9fr commented on src/component/header/example/sample/header.ejs
> +        data.menu.navigation = {
```suggestion
        navigation = {
```

2022-01-27 18:17 UTC, lab9fr commented on src/component/header/example/sample/header.ejs
> +        data.menu.navigation = {
```suggestion
        navigation = {
```

2022-01-27 18:17 UTC, lab9fr commented on src/component/header/example/sample/header.ejs
> +        data.menu.navigation = header.navigation;
```suggestion
        navigation = header.navigation;
```

2022-01-27 18:17 UTC, lab9fr commented on src/component/header/example/sample/header.ejs
> +if (hasNavbar) data.body.brand.navbar = navbar;
```suggestion
if (hasNavbar) brand.navbar = navbar;
```

2022-01-27 18:17 UTC, lab9fr commented on src/component/header/example/sample/header.ejs
> +        data.menu.navigation.id = header.navigationId || uniqueId('navigation');
```suggestion
        navigation.id = header.navigationId || uniqueId('navigation');
```

2022-01-27 18:17 UTC, lab9fr commented on src/component/header/example/sample/header.ejs
> +        data.menu.navigation.modalId = navbar.menu.modalId;
```suggestion
        navigation.modalId = navbar.menu.modalId;
```

2022-01-27 18:17 UTC, lab9fr commented on src/component/header/example/sample/header.ejs
```suggestion

const navigation = data.menu.navigation;

```

2022-01-27 18:30 UTC, lab9fr requested changes

2022-01-27 18:30 UTC, lab9fr commented on src/component/header/template/ejs/header.ejs
> +            duplicateId: ''
J'ai l'impression que c'est plus ça, duplicateId n'est utilisé nulle part, non ?
```suggestion
            duplicateLinks: false
```

2022-01-27 18:30 UTC, lab9fr commented on src/component/header/template/ejs/header.ejs
> +<% let header = locals.header || {menu: {}};
ya un truc qui manque pour le duplicateLinks, il ne fonctionne pas pour le moment.
```suggestion
<% let header = locals.header || {menu: {}};
if (header.menu.tools.duplicateLinks) header.menu.tools.links = header.body.tools.links;
```

2022-01-31 10:02 UTC, lab9fr approved these changes

2022-01-31 10:03 UTC, merged