feat(core): Ajout des valeurs d'espacement 0.5v et 1.5v [DS-2246]
GouvernementFR/dsfr pull request #174
Opened 2022-01-06 16:36 UTC by keryanS

2022-01-11 19:05 UTC, lab9fr requested changes

2022-01-11 19:05 UTC, lab9fr commented on src/core/example/spacing/sample/spacing.ejs
> +                <td><%= i < 0 ? 'n' + Math.abs(i) : i %>v</td>
une petite fonction qui sort cette partie et qui pourrait se mutualiser avec le half ?

2022-01-13 15:03 UTC, keryanS commented on src/core/example/spacing/sample/spacing.ejs
> +                <td><%= i < 0 ? 'n' + Math.abs(i) : i %>v</td>
ok

2022-01-13 15:08 UTC, lab9fr approved these changes

2022-01-13 15:09 UTC, merged