feat: ajout de la fonctionnalité share [DS-510]
GouvernementFR/dsfr pull request #21
Opened 2021-06-25 12:59 UTC by rafaelbucher

2021-06-25 13:02 UTC, lab9fr requested changes

2021-06-25 13:02 UTC, lab9fr commented on src/share/styles/_module.scss
> +    @include margin-right(calc(#{space(2v)} * -1));
@include margin-x(-2v);

2021-07-05 17:09 UTC, lab9fr requested changes

2021-07-05 17:09 UTC, lab9fr commented on src/share/.package.yml
> +doc:
Le lien pour la doc : 
https://gouvfr.atlassian.net/wiki/spaces/DB/pages/771555355/

2021-07-07 17:05 UTC, lab9fr requested changes

2021-07-07 17:05 UTC, lab9fr commented on src/share/styles/_module.scss
> +    @include max-size(#{space(72v)}, null, md);
reprendre la mixin max-width de la dev

2021-07-07 17:05 UTC, lab9fr commented on src/share/styles/_module.scss
> +  &__link {
une mixin peut-être ?

2021-07-07 17:05 UTC, lab9fr commented on src/share/templates/ejs/share-link.ejs
> +    if (tag === 'button') shareLinkAttrs['disabled'] = '';
if (tag === 'button' && shareLinkClasses.indexOf('--copy') === -1 && shareLinkClasses.indexOf('--mail') === -1)

2021-07-07 17:05 UTC, lab9fr commented on src/share/templates/ejs/share.ejs
> +                if (share.links[i].blank) dataLink.blank = share.links[i].blank;
ya du code inutile là, non ?

2021-07-08 10:22 UTC, lab9fr requested changes

2021-07-08 10:22 UTC, lab9fr commented on src/share/example/samples/share-default.ejs
> +      onclick: `window.open(this.href,'share_window','toolbar=no,location=yes,status=no,menubar=no,scrollbars=yes,resizable=yes,width=600,height=300'); event.preventDefault();`,
Factoriser les définitions des settings social avec une fonction qui renvoit un objet (param label, title, url, width, height)

2021-07-08 10:22 UTC, lab9fr commented on src/share/templates/ejs/share-link.ejs
> +    if (tag === 'button') shareLinkAttrs['disabled'] = '';
solution granularité plutôt

2021-07-08 10:22 UTC, lab9fr commented on src/share/templates/ejs/share-link.ejs
> +    shareLinkAttrs.href = locals.href || '[url - à modifier]';
contentPlaceholder

2021-07-08 10:22 UTC, lab9fr commented on src/share/templates/ejs/share.ejs
> +                if (share.links[i].blank) dataLink.blank = share.links[i].blank;
{ ... share.links[i], label:  } ou dataLink = share.links[i];
revoir sample

2021-07-09 13:32 UTC, keryanS commented on src/share/styles/_module.scss
> +  &__link {
ok

2021-07-09 13:33 UTC, keryanS commented on src/share/templates/ejs/share-link.ejs
> +    if (tag === 'button') shareLinkAttrs['disabled'] = '';
On passe tout depuis le sample maintenant, notamment les attributes

2021-07-09 13:57 UTC, keryanS commented on src/share/example/samples/share-default.ejs
> +      onclick: `window.open(this.href,'share_window','toolbar=no,location=yes,status=no,menubar=no,scrollbars=yes,resizable=yes,width=600,height=300'); event.preventDefault();`,
j'ai mis le label a la place de share_window
Création d'une fonction ok

2021-07-09 15:58 UTC, lab9fr approved these changes

2021-07-09 15:58 UTC, lab9fr commented on src/share/example/samples/share-default.ejs
> +let url = 'https://www.systeme-de-design.gouv.fr/';
à retirer

2021-07-09 15:59 UTC, merged