feat(quotes): Ajout du composant citation [DS-424]
GouvernementFR/dsfr pull request #23
Opened 2021-06-25 16:13 UTC by keryanS

ETQ développeur je souhaite disposer du composant Citation. 

Le bloc se compose: 

D’une icône illustrative - fixe & obligatoire. 
D’un texte de citation - obligatoire. 
D’un séparateur ,obligatoire.
D’un auteur - optionnel 
D’une information de source - optionnelle 
D’une image - optionnelle. 

Solution retenu : 
- Ajout d'un modificateur fr-quote--column lorsque l'on souhaite ajouter une image

2021-07-05 09:28 UTC, lab9fr requested changes

2021-07-05 09:28 UTC, lab9fr commented on src/quotes/.package.yml
> +doc:
Manque le lien de doc
@jchourdeaux , on a le lien prod ?

2021-07-05 09:28 UTC, lab9fr commented on src/quotes/example/samples/quote-default.ejs
> +   href: locals.href || 'https://lien-vers-la-source.fr',
contentPlaceholder

2021-07-05 09:28 UTC, lab9fr commented on src/quotes/example/samples/quote-with-image.ejs
> +   href: locals.href || 'https://lien-vers-la-source.fr',
contentPlaceholder

2021-07-05 09:28 UTC, lab9fr commented on src/quotes/index.scss
> +/// Alerts
quotes

2021-07-05 09:28 UTC, lab9fr commented on src/quotes/index.scss
> +/// @group alerts
idem

2021-07-05 09:28 UTC, lab9fr commented on src/quotes/index.scss
> +@import '../links/index';
dépendance à links ? si c'est le cas, modifier le yml

2021-07-05 09:28 UTC, lab9fr commented on src/quotes/main.scss
> +  ALERTS
quotes

2021-07-05 09:28 UTC, lab9fr commented on src/quotes/styles/_module.scss
> +  @include icon(chat-quote-line,lg,before) {
before est pas défault, pas nécessaire

2021-07-05 09:28 UTC, lab9fr commented on src/quotes/styles/_module.scss
> +    // todo: utiliser mixin min-height
il faudra qu'on merge share avant et que tu récupères

2021-07-05 09:28 UTC, lab9fr commented on src/quotes/styles/_module.scss
> +      // todo: utiliser mixin min-height
same

2021-07-05 09:28 UTC, lab9fr commented on src/quotes/styles/_module.scss
> +      @include respond-from(md) {
again

2021-07-05 09:33 UTC, lab9fr requested changes

2021-07-05 09:33 UTC, lab9fr commented on src/quotes/templates/ejs/quote.ejs
> +    <blockquote cite="<%= locals.contentPlaceholder(href)%>">
pas besoin de if, ça sera plus propre avec un includeAttrs

const blockAttrs = {cite: contentplaceholder}
...
<blockQute includeAttrs(blockAttrs) >

2021-07-05 09:33 UTC, lab9fr commented on src/quotes/templates/ejs/quote.ejs
> +    <p <%- (size !== undefined) ? includeClasses([prefix+'-text--'+size]) : '' %>>« <%= text %> »</p>
déclare un array textClasses  et renseignes le dans la partie config, avec juste le includeClasses, sans le test sur size

2021-07-05 14:48 UTC, keryanS commented on src/quotes/styles/_module.scss
> +    // todo: utiliser mixin min-height
En attente du merge

2021-07-05 14:49 UTC, keryanS commented on src/quotes/.package.yml
> +doc:
En attente du lien

2021-07-05 17:08 UTC, lab9fr requested changes

2021-07-05 17:08 UTC, lab9fr commented on src/quotes/.package.yml
> +doc:
et le voici: 
https://gouvfr.atlassian.net/wiki/spaces/DB/pages/771358744/

2021-07-07 16:59 UTC, lab9fr requested changes

2021-07-07 16:59 UTC, lab9fr commented on src/quotes/styles/_module.scss
> +    // todo: utiliser mixin min-height
En fait non, c'est déjà dans dev, donc tu peux récup

2021-07-07 16:59 UTC, lab9fr commented on src/quotes/.package.yml
> +doc:
up

2021-07-09 15:28 UTC, lab9fr approved these changes

2021-07-09 16:00 UTC, merged