fix(follow): separateur en box shadow
GouvernementFR/dsfr pull request #29
Opened 2021-07-20 13:21 UTC by keryanS

fix border-radius en SM
separateur en box shadow plutot que before

2021-07-21 11:39 UTC, lab9fr requested changes

2021-07-21 11:39 UTC, lab9fr commented on src/follow/styles/_module.scss
> +        // code spécifique à newwsletter seul
un w de trop dans newsletter

2021-07-21 11:39 UTC, lab9fr commented on src/follow/styles/_module.scss
> +          @include margin-bottom(0,md);
espace pour le lint avant le md je crois

2021-07-21 11:39 UTC, lab9fr commented on src/follow/styles/_schemes.scss
>      // code du séparateur en before ou box-shadow
du coup en box shadow, plus en before, non ?

2021-07-21 15:17 UTC, keryanS commented on src/follow/styles/_schemes.scss
>      // code du séparateur en before ou box-shadow
outdated

2021-07-21 15:18 UTC, keryanS commented on src/follow/styles/_module.scss
> +          @include margin-bottom(0,md);
allez pour la beauté, mais non lint ne calcul pas les espaces des params

2021-07-22 08:12 UTC, lab9fr requested changes

2021-07-22 08:12 UTC, lab9fr commented on src/follow/styles/_schemes.scss
>      // code du séparateur en before ou box-shadow
nope, c'est du commentaire que je parlais où il est question de before

2021-07-22 10:36 UTC, lab9fr approved these changes

2021-07-22 10:36 UTC, merged