fix(share): tailles des popup de partage
GouvernementFR/dsfr pull request #32
Opened 2021-07-23 10:11 UTC by keryanS

2021-07-23 14:42 UTC, lab9fr requested changes

2021-07-23 14:42 UTC, lab9fr commented on src/share/example/samples/share-default.ejs
> +      ...buildShareLink('facebook', 'Partager sur Facebook', 'https://www.facebook.com/sharer.php?u='+contentPlaceholder('url du site'), 600, 450),
j'ai l'impression qu'il manque le retour de @jchourdeaux : 

url=[À MODIFIER | url de la page]&text=[À MODIFIER | titre ou texte descriptif de la page]

pour twitter et linkedin également

2021-07-23 14:46 UTC, jchourdeaux commented on src/share/example/samples/share-default.ejs
> +      ...buildShareLink('facebook', 'Partager sur Facebook', 'https://www.facebook.com/sharer.php?u='+contentPlaceholder('url du site'), 600, 450),
@keryanS @lab9fr , et les title Partager sur xxx - ouvre une nouvelle fenêtre (sur les boutons actifs)

2021-07-23 16:09 UTC, keryanS commented on src/share/example/samples/share-default.ejs
> +      ...buildShareLink('facebook', 'Partager sur Facebook', 'https://www.facebook.com/sharer.php?u='+contentPlaceholder('url du site'), 600, 450),
OK

2021-07-26 08:05 UTC, lab9fr approved these changes

2021-07-26 08:06 UTC, merged