feat(pattern): ajoute le modele de nom et prenom [DS-2634]
GouvernementFR/dsfr pull request #356
Opened 2022-06-23 15:19 UTC by zellerbaptiste

2022-07-06 15:58 UTC, zellerbaptiste commented
Changer l'id du package pour juste 'name'

2022-07-06 16:07 UTC, keryanS commented on src/pattern/name-firstname/template/ejs/name-firstname.ejs
> +* name.items[].type (string) : type de champs à ajouter au composant, si non défini, input
ajuster les **

2022-07-06 16:07 UTC, keryanS commented on src/pattern/name-firstname/example/sample/international-name-firstname.ejs
> +            label: getText('label.no-firstname', 'name-firstname'),
unnamed

2022-07-06 16:09 UTC, zellerbaptiste commented on src/pattern/name-firstname/i18n/fr.yml
> +  default: DÉFAUT
libellés en lowercase 'Défaut'

2022-07-06 16:10 UTC, zellerbaptiste commented on src/pattern/name-firstname/i18n/fr.yml
> +    default: AVEC BOUTON
diviser les libellés et re-concatener dans les templates

2022-07-07 09:27 UTC, zellerbaptiste commented on src/pattern/name-firstname/template/ejs/name-firstname.ejs
> +* name.items[].type (string) : type de champs à ajouter au composant, si non défini, input
done

2022-07-07 09:27 UTC, zellerbaptiste commented on src/pattern/name-firstname/i18n/fr.yml
> +  default: DÉFAUT
done

2022-07-07 09:27 UTC, zellerbaptiste commented on src/pattern/name-firstname/i18n/fr.yml
> +    default: AVEC BOUTON
done

2022-07-19 16:33 UTC, keryanS requested changes

2022-07-20 09:02 UTC, zellerbaptiste commented on src/pattern/name/template/ejs/name.ejs
> +fieldset.attributes = { 'aria-label': name.label,}
dans le cas ou le fieldset ne comporte pas de `<legend>` il faut ajouter l'attribut `aria-label`

2022-07-22 18:17 UTC, merged