feat(page-error): ajoute les modeles de page erreur 404 [DS-1941]
GouvernementFR/dsfr pull request #371
Opened 2022-07-12 14:26 UTC by zellerbaptiste

2022-07-19 14:40 UTC, keryanS requested changes

2022-07-19 14:40 UTC, keryanS commented on src/page/response/template/ejs/response.ejs
>                      <use class="fr-artwork-motif" xlink:href="<%= relativeRoot %>dist/artwork/artwork-background.svg#artwork-motif"></use>
modifier les prefix "fr-" en <%= prefix %>-
nom du pictogramme de fond à changer, pas besoin du prefix "artwork-" et "background" trop large.

Est-ce qu'on est toujours bien centré avec le translate en px et le fr-responsive img qui est en fonction de la taille de conteneur ?

2022-07-19 14:48 UTC, keryanS requested changes

2022-07-19 14:48 UTC, keryanS commented on src/core/asset/artwork/artwork-background.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" viewBox="0 0 160 200">
Ajouter la width height
Ajouter xmlns:xlink="http://www.w3.org/1999/xlink"
xml:space="preserve" pas utile à priori

2022-07-19 16:01 UTC, zellerbaptiste commented on src/page/response/template/ejs/response.ejs
> +                    <use class="fr-artwork-motif" xlink:href="<%= relativeRoot %>dist/artwork/artwork-background.svg#artwork-motif"></use>
A tester sur ie11

```suggestion
                    <use class="fr-artwork-motif" href="<%= relativeRoot %>dist/artwork/artwork-background.svg#artwork-motif"></use>
```

2022-07-19 16:07 UTC, zellerbaptiste commented on src/core/asset/artwork/artwork-background.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" viewBox="0 0 160 200">
changer le nom du fichier pour un nom plus générique ("potate-background" par ex)

2022-07-20 20:30 UTC, lab9fr approved these changes

2022-07-20 20:35 UTC, merged