refactor(form): Ajout des fr-control et correction des pattern civility & name
GouvernementFR/dsfr pull request #401
Opened 2022-09-12 15:40 UTC by keryanS

2022-09-19 14:12 UTC, lab9fr requested changes

2022-09-19 14:12 UTC, lab9fr commented on src/component/form/style/_module.scss
> +  $control: #{&};
```suggestion

```

2022-09-19 14:12 UTC, lab9fr commented on src/component/form/style/_module.scss
> +
```suggestion
}

```

2022-09-19 14:12 UTC, lab9fr commented on src/component/form/style/_module.scss
> +    &:not(#{$control}--inline) {
```suggestion
&--postal:not(&--inline) {
```

2022-09-19 14:12 UTC, lab9fr commented on src/component/form/style/_module.scss
>      }
```suggestion
```

2022-09-19 14:12 UTC, lab9fr commented on src/component/form/style/_module.scss
> +
```suggestion
}

```

2022-09-19 14:12 UTC, lab9fr commented on src/component/form/style/_module.scss
> +    &:not(#{$control}--inline) {
```suggestion
&--number:not(&--inline) {
```

2022-09-19 14:12 UTC, lab9fr commented on src/component/form/style/_module.scss
>      }
```suggestion
```

2022-09-19 14:12 UTC, lab9fr commented on src/component/radio/style/module/_rich.scss
> +// #{ns(fieldset)} {
à cleaner ?

2022-09-19 14:12 UTC, lab9fr commented on src/pattern/address/example/sample/data/country.ejs
> +<%
mettre au format json peut-être ?
Plus facile à transposer pour les utilisateurs.

2022-09-26 08:39 UTC, lab9fr requested changes

2022-09-26 08:39 UTC, lab9fr commented on src/component/form/deprecated/style/_module.scss
> +// [DEPRECATED]
```suggestion
```

2022-09-26 08:39 UTC, lab9fr commented on src/component/form/style/_module.scss
> +  $control: #{&};
```suggestion
```

2022-09-26 08:39 UTC, lab9fr commented on src/component/radio/style/module/_default.scss
> +    // input[type="radio"] + label {
à supprimer ?

2022-09-26 08:39 UTC, lab9fr commented on src/component/toggle/example/sample/toggle-group.ejs
> +  hint: toggle.hint === true ? 'Texte d’aide pour clarifier l’action' : toggle.hint,
i18n ?

2022-09-26 08:39 UTC, lab9fr commented on src/pattern/civility/template/ejs/civility.ejs
> +      data: {
prévoir une fonction ejs dans decorator pour mutualiser avec name si c'est bien le même système ?
on en discute.

2022-09-26 08:39 UTC, lab9fr commented on src/pattern/name/example/sample/international-and-firstname-disabled.ejs
> +            attributes: {onclick: `const control = this.closest('.fr-control'); const firstnameControl = control.previousElementSibling; const firstnameInput = firstnameControl.querySelector('input')
un control builder pour simplifier et mutualiser ?

2022-09-26 09:32 UTC, keryanS commented on src/pattern/name/example/sample/international-and-firstname-disabled.ejs
> +            attributes: {onclick: `const control = this.closest('.fr-control'); const firstnameControl = control.previousElementSibling; const firstnameInput = firstnameControl.querySelector('input')
J'ai créé un template form dans login/register pour interfacer ça, il faudra revenir sur ces modèles pour l'utiliser.

2022-09-26 09:32 UTC, keryanS commented on src/component/toggle/example/sample/toggle-group.ejs
> +  hint: toggle.hint === true ? 'Texte d’aide pour clarifier l’action' : toggle.hint,
A mettre en place plus globalement sur toggle non ?

2022-09-26 09:32 UTC, keryanS commented on src/pattern/address/example/sample/data/country.ejs
> +<%
On peut accéder à getText en json ?

2022-09-26 09:32 UTC, keryanS commented on src/pattern/civility/template/ejs/civility.ejs
> +      data: {
voir #403 -> form/template/ejs/form.ejs

2022-09-26 09:34 UTC, keryanS commented on src/component/toggle/example/sample/toggle-group.ejs
> +  hint: toggle.hint === true ? 'Texte d’aide pour clarifier l’action' : toggle.hint,
C'était juste un fixe rapide des groupe de toggle avec hint qui affichait true.

2022-09-26 16:38 UTC, keryanS commented on src/pattern/address/example/sample/data/country.ejs
> +<%
Interface avec fichier json

2022-09-28 15:54 UTC, lab9fr approved these changes

2022-09-28 16:16 UTC, merged