fix(tabs): Ouverture de modal à l'intérieur d'un composant onglet [DS-2731]
GouvernementFR/dsfr pull request #405
Opened 2022-09-19 13:37 UTC by zellerbaptiste

2022-09-26 08:46 UTC, lab9fr requested changes

2022-09-26 08:46 UTC, lab9fr commented on src/component/tab/style/module/_default.scss
> +        0 1px;
pourquoi à la ligne ?

2022-09-26 08:46 UTC, lab9fr commented on src/component/tab/style/module/_default.scss
> +      transform $tabs-transition-duration;
pourquoi à la ligne ?

2022-09-27 08:12 UTC, zellerbaptiste commented on src/component/tab/style/module/_default.scss
> +      100% 100%;
ah oui c'est mon prettier ;)

2022-09-27 12:43 UTC, zellerbaptiste commented on src/component/tab/style/module/_default.scss
> +      100% 100%;
c'est corrigé

2022-09-27 12:43 UTC, zellerbaptiste commented on src/component/tab/style/module/_default.scss
> +        0 1px;
c'est corrigé

2022-09-27 12:43 UTC, zellerbaptiste commented on src/component/tab/style/module/_default.scss
> +      transform $tabs-transition-duration;
c'est corrigé

2022-10-14 11:33 UTC, merged