feat(transcription): ajoute le composant transcription
GouvernementFR/dsfr pull request #412
Opened 2022-09-27 10:14 UTC by zellerbaptiste

2022-09-27 15:39 UTC, lab9fr requested changes

2022-09-27 15:39 UTC, lab9fr commented on src/component/transcription/style/_module.scss
> +          &--tertiary-no-outline {
normalement, tu dois pouvoir intégrer le bouton avec la mixin nest-btn je pense
@include nest-btn(md, right, menu-2-fill, null, true, true);
regarde du côté de la search bar, il y a un nesting de bouton avec l'icone seule en mobile

2022-09-27 15:39 UTC, lab9fr commented on src/component/transcription/style/_module.scss
> +        color: var(--text-action-high-blue-france);
à mettre dans le fichier scheme

2022-09-27 15:39 UTC, lab9fr commented on src/component/transcription/style/_module.scss
> +          position: absolute;
pourquoi en absolute ?
à priori, c'est en inline ici

2022-09-27 15:39 UTC, lab9fr commented on src/component/transcription/style/_module.scss
> +          position: absolute;
idem

2022-09-27 15:39 UTC, lab9fr commented on src/component/transcription/style/_module.scss
> +        --transcription-detail-max-width: 5.25rem;
plutôt que de jouer sur une taille fixe, jouer sur des rapport de taille je dirais.
avec du shrink sur le premier élémentet un max-width:100% sur le download, ça devrait marcher
<img width="485" alt="Screenshot 2022-09-27 at 17 30 48" src="https://user-images.githubusercontent.com/142149/192571017-8f10b3c9-6ee1-4c9a-bc47-e247988ea5a1.png">

2022-09-27 15:39 UTC, lab9fr commented on src/component/transcription/template/ejs/transcription.ejs
> +<div class="<%= prefix %>-transcription">
à revoir en utilisant les template de modal et download

2022-09-27 15:57 UTC, zellerbaptiste commented on src/component/transcription/style/_module.scss
> +          position: absolute;
la parenthèse est placée en absolute pour pouvoir l'afficher meme avec le `text-overflow: ellipsis;` et obtenir le meme rendu que la maquette : 
![Capture d’écran 2022-09-27 à 17 57 01](https://user-images.githubusercontent.com/10864245/192575883-41537caa-09c6-4d74-9495-d8dad4babca8.png)

2022-09-27 15:59 UTC, zellerbaptiste commented on src/component/transcription/style/_module.scss
> +        overflow: hidden;
yes je les retire ici 👍

2022-09-27 16:10 UTC, zellerbaptiste commented on src/component/transcription/style/_module.scss
> +          &--tertiary-no-outline {
Exemple du search pour l'icone only sur mobile
<img width="332" alt="Capture d’écran 2022-09-27 à 18 09 20" src="https://user-images.githubusercontent.com/10864245/192578710-4b4253dc-1c89-49d2-a62f-5ad21b7e516a.png">

2022-09-29 15:21 UTC, zellerbaptiste commented on src/component/transcription/style/_module.scss
> +          position: absolute;
cf commentaire sur l'autre parenthèse

2022-09-30 10:21 UTC, zellerbaptiste commented on src/component/transcription/style/_module.scss
> +        color: var(--text-action-high-blue-france);
c'est corrigé

2022-09-30 10:21 UTC, zellerbaptiste commented on src/component/transcription/style/_module.scss
> +          &--tertiary-no-outline {
c'est corrigé

2022-09-30 10:21 UTC, zellerbaptiste commented on src/component/transcription/style/_module.scss
> +        --transcription-detail-max-width: 5.25rem;
c'est corrigé

2022-09-30 10:21 UTC, zellerbaptiste commented on src/component/transcription/template/ejs/transcription.ejs
> +<div class="<%= prefix %>-transcription">
c'est corrigé

2022-09-30 10:22 UTC, zellerbaptiste commented on src/component/transcription/style/_module.scss
> +          &--tertiary-no-outline {
à revoir ensemble car le mode "only" se semble pas fonctionner sur mobile

2022-09-30 14:46 UTC, zellerbaptiste commented on src/component/transcription/style/_module.scss
> +          &--tertiary-no-outline {
ça fonctionne 👍

2022-10-07 10:27 UTC, lab9fr requested changes

2022-10-07 10:27 UTC, lab9fr commented on tool/example/decorator.ejs
> +const randomContent = (textonly = false, id) => {
plutôt dans l'autre sens les arguments, le paramètre optionnel venant en dernier, ça permet d'être sûr de ne pas toucher les précédentes implémentations.

Ensuite, si on rajoute cette option, je serai plutôt partisan d'avoir un contrôle plus fin sur le contenu, avec un array listant les types de contenu que tu parcours pour ajouter à content chaque type.

```suggestion
const randomContent = (id, types = ['title', 'img', 'text', 'list']) => {
```

2022-10-07 12:02 UTC, zellerbaptiste commented on tool/example/decorator.ejs
> +const randomContent = (textonly = false, id) => {
Ok je vois ton point mais en parcourant les utilisations de cette méthode c'est plutôt l'id qui est optionnel car il n'est utilisé qu'une seule fois.

2022-10-11 09:44 UTC, lab9fr approved these changes

2022-10-14 14:44 UTC, merged