feat(upload): ajout du composant upload [DS-1918]
GouvernementFR/dsfr pull request #43
Opened 2021-08-10 15:05 UTC by keryanS

raf: lien doc

2021-08-11 08:46 UTC, lab9fr requested changes

2021-08-11 16:03 UTC, keryanS commented on src/upload/.package.yml
> +  - inputs
erreur de copié collé

2021-09-02 12:02 UTC, lab9fr approved these changes

2021-09-16 17:17 UTC, lab9fr requested changes

2021-09-16 17:17 UTC, lab9fr commented on src/component/upload/style/_module.scss
> +}
il a l'air de dire que ya pas de line break à la fin du fichier

2021-09-24 15:23 UTC, lab9fr requested changes
Manque le lien vers la doc
En attente de @jchourdeaux

2021-09-27 17:25 UTC, lab9fr requested changes

2021-09-27 17:25 UTC, lab9fr commented on src/component/upload/style/_module.scss
> +    &::-webkit-file-upload-button{
à checker avec le reset

2021-11-04 10:33 UTC, lab9fr approved these changes

2021-11-04 10:34 UTC, merged