feat(pagination): border active sur version constrasté [DS-2717]
GouvernementFR/dsfr pull request #436
Opened 2022-10-27 09:13 UTC by keryanS

2022-10-28 15:36 UTC, lab9fr requested changes

2022-10-28 15:36 UTC, lab9fr commented on src/component/pagination/style/_contrast.scss
> +  @media (prefers-contrast: more) {
@keryanS le support de cette media query est un peu léger.
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/forced-colors me semble plus recommandé vu que c'est edge qui est visé en combination avec -ms-high-contrast pour supporter encore avant.
à discuter

2022-11-03 15:31 UTC, lab9fr requested changes

2022-11-03 17:04 UTC, keryanS commented on src/component/pagination/style/_scheme.scss
> +        @include color.box-shadow(active blue-france, (legacy: $legacy), all-1-in);
résidu

2022-11-03 17:07 UTC, keryanS commented on src/component/pagination/style/_contrast.scss
> +          @include color.border(active blue-france, (legacy: $legacy, hover: true));
j'ai mis un calc sur le padding. mais comme c'est un scheme => if not legacy (pour éviter de dupliquer)

2022-11-03 17:08 UTC, keryanS commented on module/contrast/mixin/_selector.scss
> +@mixin selector() {
j'ai mis high-contrast() c'est plus parlant et plus modulaire si on a un low-contrast() ou custom-contrast() un jour

2022-11-04 22:59 UTC, lab9fr requested changes

2022-11-04 22:59 UTC, lab9fr commented on src/component/pagination/style/_contrast.scss
> +          @include color.border(active blue-france, (legacy: $legacy, hover: true));
pour être conforme avec ce qui va venir par la suite, je dirais de faire 2 mixin, une _pagination-contrast-scheme($legacy) et une _pagination-contrast avec le padding et d'appeler ensuite les 2 de la manière appropriée

2022-11-08 10:13 UTC, lab9fr approved these changes

2022-11-08 10:14 UTC, merged