fix(core): ajout de la fonctionnalité d'ouverture des disclose à partir des ancres [DS-2805]
GouvernementFR/dsfr pull request #463
Opened 2022-11-14 21:05 UTC by lab9fr

2022-11-15 15:55 UTC, keryanS requested changes

2022-11-15 15:55 UTC, keryanS commented on src/core/script/disclosure/disclosure.js
> +    console.log('hash', this.id, !withhold, this.hash);
```suggestion

```

2022-11-16 15:37 UTC, keryanS requested changes

2022-11-16 15:37 UTC, keryanS commented on src/core/script/collapse/collapse-button.js
> +    console.log(this.node, ip);
```suggestion

```

2022-11-16 15:37 UTC, keryanS commented on src/core/example/collapse/sample/collapse.ejs
> +    <% for (let i = 0; i < 1; i++) {
for 0 to 1 ? 
on peut enlever le for ?

2022-11-16 15:37 UTC, keryanS commented on src/core/example/collapse/sample/collapse.ejs
> +            <%- include('../../../../component/button/template/ejs/button.ejs', {button: button}); %>
2 fois le même bouton ? 
nested ?

2022-11-16 15:43 UTC, keryanS commented
Quand on recharge la page avec le meme id le collapse/modal ne se rouvre pas.

2022-11-17 13:32 UTC, zellerbaptiste commented
> Details

Le reload fonctionne bien pour les accordéons mais toujours pas pour les onglets : 
https://deploy-preview-463--ds-gouv.netlify.app/example/component/tab#tabpanel-1165-panel

2022-11-17 13:35 UTC, zellerbaptiste requested changes
Le reload fonctionne bien pour la modale et les accordéons mais toujours pas pour les onglets :
https://deploy-preview-463--ds-gouv.netlify.app/example/component/tab#tabpanel-1165-panel

2022-11-17 17:13 UTC, lab9fr commented
> Le reload fonctionne bien pour la modale et les accordéons mais toujours pas pour les onglets : https://deploy-preview-463--ds-gouv.netlify.app/example/component/tab#tabpanel-1165-panel

Normalement, c'est corrigé

2022-11-18 10:10 UTC, zellerbaptiste approved these changes

2022-11-18 10:10 UTC, zellerbaptiste commented
> > Le reload fonctionne bien pour la modale et les accordéons mais toujours pas pour les onglets : https://deploy-preview-463--ds-gouv.netlify.app/example/component/tab#tabpanel-1165-panel
> 
> Normalement, c'est corrigé

C'est ok pour moi

2022-11-21 14:05 UTC, keryanS requested changes

2022-11-21 14:05 UTC, keryanS commented on src/core/script/disclosure/disclosures-group.js
> +    console.log(this.index, defaultIndex, index);
```suggestion
```

2022-11-21 18:02 UTC, merged