:tada: feat(tooltip): ajout de la fonctionnalité Tooltip [DS-2900,DS-3234]
GouvernementFR/dsfr pull request #486
Opened 2022-11-29 14:35 UTC by zellerbaptiste

Le composant `Infobulle` (ou `bulle d’aide`, `aide contextuelle`) permet d’afficher du contenu dans le contexte de navigation (non modal), à propos et lors de l’interaction avec un élément précis de l’interface. Il est caché par défaut, et s’affiche au survol ou au clic de l’élément associé, par-dessus le reste de la page.

2022-12-09 14:45 UTC, lab9fr requested changes

2022-12-09 14:45 UTC, lab9fr commented on src/component/tooltip/.package.yml
> +  - button
share input et table non plus, ce sont des dépendances d'exemple

2022-12-09 14:45 UTC, lab9fr commented on src/component/tooltip/style/_module.scss
> +  max-width: min(spacing.space(96v), spacing.space(calc((100vw - 8v) * 2 / 3)));
```suggestion
  @include spacing.max-width(min(96v, calc((100vw - 8v) * 2 / 3));
```

2022-12-09 14:45 UTC, lab9fr commented on src/component/tooltip/style/_module.scss
> +    border-width: spacing.space(1.5v) spacing.space(1v) 0 spacing.space(1v);
```suggestion
    border-width: spacing.space(1.5v 1v 0 1v);
```

2022-12-09 14:45 UTC, lab9fr commented on src/component/tooltip/style/_module.scss
> +    left: calc(50% - #{spacing.space(0.75v)});
```suggestion
    left: spacing.space(calc(50% - 0.75v));
```

2022-12-09 14:45 UTC, lab9fr commented on src/component/tooltip/style/_module.scss
> +    border-width: spacing.space(1.5v) spacing.space(1v) 0 spacing.space(1v);
```suggestion
    border-width: spacing.space(1.5v 1v 0 1v);
```

2022-12-09 14:45 UTC, lab9fr commented on src/component/tooltip/style/_module.scss
> +    left: calc(50% - #{spacing.space(0.75v)});
```suggestion
    left: spacing.space(calc(50% - 0.75v));
```

2022-12-09 14:45 UTC, lab9fr commented on src/component/tooltip/style/_module.scss
> +        border-width: 0 spacing.space(1v) spacing.space(1.5v) spacing.space(1v);
```suggestion
        border-width: spacing.space(0 1v 1.5v 1v) ;
```

2022-12-09 14:45 UTC, lab9fr commented on src/component/tooltip/style/_module.scss
> +        border-width: 0 spacing.space(1v) spacing.space(1.5v) spacing.space(1v);
```suggestion
        border-width: spacing.space(0 1v 1.5v 1v);
```

2022-12-09 14:45 UTC, lab9fr commented on src/core/index.js
> +  TooltipEvent: TooltipEvent
devrait être dans le package tooltip, pas dans el core

2022-12-12 10:18 UTC, zellerbaptiste commented on src/component/tooltip/style/_module.scss
> +  max-width: min(spacing.space(96v), spacing.space(calc((100vw - 8v) * 2 / 3)));
cette mixin n'existe pas encore, tu voudrais l'ajouter ?

2022-12-12 10:29 UTC, zellerbaptiste commented on src/component/tooltip/style/_module.scss
> +    left: calc(50% - #{spacing.space(0.75v)});
ne passe pas le linter

2022-12-12 10:30 UTC, zellerbaptiste commented on src/component/tooltip/style/_module.scss
> +    left: calc(50% - #{spacing.space(0.75v)});
ne passe pas le linter

2022-12-12 10:35 UTC, zellerbaptiste commented on src/component/tooltip/style/_module.scss
> +    left: calc(50% - #{spacing.space(0.75v)});
`Expected a valid expression (function-calc-no-invalid)`

2022-12-12 15:40 UTC, zellerbaptiste commented
@lab9fr j'ai pris en compte tes retours

2023-01-02 14:42 UTC, keryanS requested changes
@zellerbaptiste @lab9fr 

Rendu étrange sur voice-over, 
- Tooltip avec zone d’action (au clic) : Le texte du tooltip est lu 2 fois
- Dans le groupe de lien il n'est pas du tout annoncé.
- sur le bouton input OK

Pourquoi mettre le tooltip en dehors et aussi loin du bouton ? on serait plus logique en mettant le span à l'intérieur. ça pourait aussi corrigé le souci de voice-over, plus besoin de aria-described qui n'est pas toujours lu (apparemment dans la liste) et pas de double lecture.
De plus, la question de est-ce que c'est valide de mettre un <span> en dehors d'un <p> ne se poserai plus.

La logique entre affichage au click et au survol ne devrait pas être entre fonction de la balise utilisée (button = click, a = hover), on devrait pouvoir survoler un button aussi (copié url par exemple)

Je me demande si on devrait pas mettre un léger délai avant d'afficher au survol, pour éviter un flash lorsque l'on passe dessus sans faire exprès.

2023-01-05 10:48 UTC, zellerbaptiste commented on src/component/tooltip/style/_module.scss
> +  transition: opacity 0.3s, visibility 0.3s;
Retirer les transitions

2023-01-05 10:52 UTC, zellerbaptiste commented on src/component/tooltip/style/_module.scss
> +  &:not(&--shown) {
Retirer les transitions

2023-01-05 11:01 UTC, zellerbaptiste commented on src/component/tooltip/style/_module.scss
> +  transition: opacity 0.3s, visibility 0.3s;
ajouter un delay 0.15s

2023-01-05 11:54 UTC, zellerbaptiste commented on src/component/tooltip/style/_module.scss
> +  transition: opacity 0.3s, visibility 0.3s;
ajouter pointer-event: none;

2023-01-05 11:55 UTC, zellerbaptiste commented on src/component/tooltip/style/_scheme.scss
> +  #{ns(tooltip)} {
ajouter couleur de texte par defaut

2023-01-05 11:56 UTC, zellerbaptiste commented on src/component/tooltip/style/_module.scss
> +  transition: opacity 0.3s, visibility 0.3s;
ajouter text-align: center;

2023-01-05 14:28 UTC, zellerbaptiste commented on src/component/tooltip/style/_module.scss
> +  transition: opacity 0.3s, visibility 0.3s;
done

2023-01-06 14:10 UTC, zellerbaptiste commented
J'ai refactoré les templates pour placer les tooltips à coté de leur déclencheur.

2023-01-06 14:10 UTC, zellerbaptiste commented on src/component/tooltip/style/_module.scss
> +  &:not(&--shown) {
done

2023-01-06 14:10 UTC, zellerbaptiste commented on src/component/tooltip/style/_scheme.scss
> +  #{ns(tooltip)} {
done

2023-01-09 14:43 UTC, keryanS requested changes

2023-01-09 14:43 UTC, keryanS commented on src/component/tooltip/example/sample/tooltip-button.ejs
> +  classes: ['fr-btn--tooltip'],
utilisation de prefix à la place de 'fr'

2023-01-09 14:43 UTC, keryanS commented on src/component/tooltip/example/sample/tooltip-grid.ejs
> +      content: `<a class="fr-link" href="#" aria-describedby="${tooltipId}">Exemple</a>${tooltipExample}`
prefix
et "exemple" en i18n

2023-01-09 14:43 UTC, keryanS commented on src/component/tooltip/example/sample/tooltip-table.ejs
> +      '<p class="fr-badge fr-badge--success fr-badge fr-badge--success">Livré</p>',
prefix plutot que 'fr'

2023-01-09 14:43 UTC, keryanS commented on src/component/tooltip/example/sample/tooltip-text.ejs
> +let tooltipTarget = `<span class="fr-text--bold" aria-describedby="${tooltipId}">${triggerText}</span>`;
prefix

'Exemple' i18n

2023-01-09 14:43 UTC, keryanS commented on src/component/tooltip/style/_legacy.scss
> +          max-height: spacing.space(38v);
@include max-height(38v) ?

2023-01-09 14:43 UTC, keryanS commented on src/component/tooltip/style/_module.scss
> +  @include max-width('min(96v, calc((100vw - 8v) * 2 / 3))');
C'est pour ça le stylelint du calc() désactivé ? On peut peut être faire une partie du calcul en sass ?

2023-01-09 14:43 UTC, keryanS commented on src/component/tooltip/style/_scheme.scss
> +        @include color.background-image((overlap grey) (border default grey), (legacy: $legacy), 'conic-gradient(from -33.69deg at 50% 100%, transparent 0deg, $color#1 0deg, $color#1 67.38deg, transp
mettre les gradiant dans une mixin dans tool, et mutualiser

2023-01-09 14:43 UTC, keryanS commented on src/core/style/placement/_module.scss
> +  position: fixed;
@include fixed(0, null,null,0)

2023-01-09 14:53 UTC, lab9fr commented on src/component/tooltip/style/_module.scss
> +  @include max-width('min(96v, calc((100vw - 8v) * 2 / 3))');
il me semble que c'est le min qui pose problème parce que c'est à la fois une fonction sass et une fonction css

2023-01-09 14:56 UTC, keryanS reviewed
proposition d'ajustements sur la page d'exemple : 
- Infobulle -> sutitle: 'ouverture du tooltip au click'
- ajout d'un exemple info bulle en situation ?
- Information contextuelle -> nouvel exemple, avec tooltip à gauche.  sutitle: 'ouverture du tooltip au survol'
- information contextuelle en bout de ligne
- information contextuelle dans un texte
- information contextuelle dans une liste -> déplacer cet exemple ici
- information contextuelle dans un tableau

2023-01-09 17:04 UTC, zellerbaptiste commented on src/component/tooltip/style/_module.scss
> +  @include max-width('min(96v, calc((100vw - 8v) * 2 / 3))');
pour être exact c'est sur la ligne 20 que le linter saute : 
`/Users/zellerbaptiste/Code/dsfr/src/component/tooltip/style/_module.scss:20:137: Expected a valid expression (function-calc-no-invalid) [error]`

`background-position: spacing.space(calc(50% + var(--arrow-x)) calc(100% - 2v)), spacing.space(calc(50% + var(--arrow-x)) calc(100% - 1.5v)), spacing.space(50% calc(100% - 3v)), spacing.space(50% calc(100% - 3v));`

2023-01-09 17:26 UTC, zellerbaptiste commented on src/component/tooltip/example/sample/tooltip-text.ejs
> +let tooltipTarget = `<span class="fr-text--bold" aria-describedby="${tooltipId}">${triggerText}</span>`;
done

2023-01-09 17:26 UTC, zellerbaptiste commented on src/component/tooltip/example/sample/tooltip-table.ejs
> +      '<p class="fr-badge fr-badge--success fr-badge fr-badge--success">Livré</p>',
done

2023-01-09 17:26 UTC, zellerbaptiste commented on src/component/tooltip/example/sample/tooltip-grid.ejs
> +      content: `<a class="fr-link" href="#" aria-describedby="${tooltipId}">Exemple</a>${tooltipExample}`
done

2023-01-09 17:26 UTC, zellerbaptiste commented on src/component/tooltip/example/sample/tooltip-button.ejs
> +  classes: ['fr-btn--tooltip'],
done

2023-01-09 17:26 UTC, zellerbaptiste commented on src/core/style/placement/_module.scss
> +  position: fixed;
done

2023-01-10 08:49 UTC, zellerbaptiste commented on src/component/tooltip/style/_module.scss
> +  @include max-width('min(96v, calc((100vw - 8v) * 2 / 3))');
je suis preneur de piste de correctif @keryanS @lab9fr

2023-01-10 08:50 UTC, zellerbaptiste commented on src/component/tooltip/style/_scheme.scss
> +        @include color.background-image((overlap grey) (border default grey), (legacy: $legacy), 'conic-gradient(from -33.69deg at 50% 100%, transparent 0deg, $color#1 0deg, $color#1 67.38deg, transp
yes je veux bien un coup de main sur cette partie @lab9fr

2023-01-11 13:02 UTC, zellerbaptiste commented on src/component/tooltip/style/_scheme.scss
> +        @include color.background-image((overlap grey) (border default grey), (legacy: $legacy), 'conic-gradient(from -33.69deg at 50% 100%, transparent 0deg, $color#1 0deg, $color#1 67.38deg, transp
done

2023-01-26 10:22 UTC, lab9fr submitted a review, later dismissed

2023-06-22 15:25 UTC, keryanS approved these changes

2023-06-22 15:26 UTC, merged