feat(name): ajout bouton de suppression de prénom [DS-2974]
GouvernementFR/dsfr pull request #493
Opened 2022-12-09 18:19 UTC by keryanS

2022-12-13 15:45 UTC, lab9fr requested changes

2022-12-13 15:45 UTC, lab9fr commented on src/pattern/name/example/data/js/add-firstname.js
> +const labelRemoveButton = 'Supprimer le prénom';
mettre dans le i18n le label supprimer le prénom

2022-12-23 16:42 UTC, lab9fr requested changes

2022-12-23 16:42 UTC, lab9fr commented on src/pattern/name/example/data/js/add-firstname.js
> +
à optimiser

2022-12-23 18:02 UTC, keryanS commented on src/pattern/name/example/data/js/add-firstname.js
> +
Optimiser comment ?

2023-06-15 14:25 UTC, lab9fr requested changes

2023-06-15 14:25 UTC, lab9fr commented on src/component/input/input-base/example/sample/input-action.ejs
> +input.button = input.button || {label:'Supprimer le champs', kind: 2, icon: 'delete-line', type: 'button'};
Supprimer le champs => à mettre dans le i18n

2023-06-15 16:36 UTC, keryanS commented on src/component/input/input-base/example/sample/input-action.ejs
> +input.button = input.button || {label:'Supprimer le champs', kind: 2, icon: 'delete-line', type: 'button'};
ok

2023-06-16 10:33 UTC, lab9fr approved these changes

2023-06-16 10:38 UTC, merged