refactor(radio,checkbox,toggle): passage input en bleu et refactorisation
GouvernementFR/dsfr pull request #502
Opened 2022-12-21 15:24 UTC by keryanS

toggle:
Ajout des toggles error/valid
Input appearance & bordure en svg
toggle dans un fieldset

radio:
contour bleu
input en background image

checkbox:
contour bleu

2022-12-23 17:36 UTC, lab9fr requested changes

2022-12-23 17:36 UTC, lab9fr commented on src/component/radio/deprecated/style/_module.scss
> +          background-position: calc(-#{space(1v)} + 1px) calc(#{space(2v)} + 1px), calc(-#{space(1v)} + 1px) calc(#{space(2v)} + 1px);
la fonction space comprend calc, il y a besoin de la mettre que 2 fois.
utiliser la version module

2022-12-23 17:36 UTC, lab9fr commented on src/component/radio/deprecated/style/_module.scss
> +          background-position: calc(-#{space(0.5v)} + 1px) calc(#{space(4v)} - 1px), calc(-#{space(0.5v)} + 1px) calc(#{space(4v)} - 1px);
idem, fonction space

2022-12-23 17:36 UTC, lab9fr commented on src/component/radio/deprecated/style/_module.scss
> +          background-position: calc(-#{space(1v)} + 1px) calc(#{space(2v)} + 1px), calc(-#{space(1v)} + 1px) calc(#{space(2v)} + 1px);
background-position: space(calc(-1v + 1px) calc(2v + 1px)), space(calc(-1v + 1px) calc(2v + 1px));

2022-12-23 17:36 UTC, lab9fr commented on src/component/checkbox/style/_scheme.scss
> +          @include color.box-shadow(border plain error, (legacy:$legacy));
background-image ?

2022-12-23 17:36 UTC, lab9fr commented on src/component/radio/style/module/_rich.scss
> +      background-size: 100% 1px, 1px 100%, 100% 1px, 1px 100%, #{space(4.5v)} #{space(4.5v)}, #{space(4.5v)} #{space(4.5v)};
implémentation de space

2022-12-23 17:36 UTC, lab9fr commented on src/component/radio/style/module/_rich.scss
> +      background-position: 0 0, 100% 0, 0 100%, 0 0, #{space(7v)} 50%, #{space(7v) 50%};
idem

2022-12-23 17:36 UTC, lab9fr commented on src/component/radio/style/module/_sm.scss
> +      background-position: calc(-#{space(0.5v)} + 1px) calc(#{space(1v)} - 1px), calc(-#{space(0.5v)} + 1px) calc(#{space(1v)} - 1px);
implémnetation de space

2022-12-23 17:36 UTC, lab9fr commented on src/component/radio/style/module/_sm.scss
> +      background-size: #{space(4.5v)} #{space(4.5v)}, #{space(4.5v)} #{space(4.5v)};
idem

2023-01-02 10:30 UTC, keryanS commented on src/component/checkbox/style/_scheme.scss
> +          @include color.box-shadow(border plain error, (legacy:$legacy));
Trop compliqué de dessiner la bordure d'1px avec le radius en background image. Sauf en la dessinant en svg (comme sur toggle) mais peut être overkill. la box-shadow m'a semblé rester la meilleur solution ici

2023-06-15 14:55 UTC, lab9fr approved these changes

2023-06-19 08:52 UTC, merged