fix(content): Le composant media ne fonctionne pas avec une image svg [DS-1966]
GouvernementFR/dsfr pull request #54
Opened 2021-09-13 13:49 UTC by keryanS

Fonctionne maintenant avec n'importe quelle balise placée directement après content-media__img

2021-09-13 17:33 UTC, lab9fr requested changes

2021-09-13 17:33 UTC, lab9fr commented on src/component/content/style/_module.scss
> +    > * {
pour le coup, est-ce qu'on mettrait pas un class BEM, genre &-asset pour avoir fr-content-media__img-asset ?

2021-09-14 12:21 UTC, keryanS commented on src/component/content/style/_module.scss
> +    > * {
fonctionne avec fr-content-media__asset et > *
+ Ajout d'exemple
+ fix gitignore

2021-09-14 16:09 UTC, lab9fr approved these changes

2021-09-14 16:09 UTC, merged