feat(badge): Ajout du composant Badge [DS-1921]
GouvernementFR/dsfr pull request #59
Opened 2021-09-14 11:16 UTC by keryanS

2021-09-16 17:16 UTC, lab9fr requested changes

2021-09-16 17:16 UTC, lab9fr commented on src/component/badge/example/index.js
> +import './_index.scss';
sans le ./

2021-09-16 17:16 UTC, lab9fr commented on src/component/badge/main.scss
> +@import './index';
sans le ./

2021-09-16 17:16 UTC, lab9fr commented on src/component/badge/scheme.scss
> +@import './index';
sans le ./

2021-09-16 17:16 UTC, lab9fr commented on src/component/link/style/tool/_icon.scss
> +    // overflow: initial;
pourquoi commenter cette partie ? ça peut causer des soucis dans le cadre d'une icone seule qui est nestée comme dans le menu il me semble

2021-09-16 17:16 UTC, lab9fr commented on src/component/link/style/tool/_size.scss
> +  $padding-y: if($min-height - $space-y > 0, ($min-height - $space-y) / 2, 0);
il me semble que t'as min comme fonction math que tu peux utiliser là
https://sass-lang.com/documentation/values/calculations#min-and-max

2021-09-16 17:16 UTC, lab9fr commented on src/core/style/display/module/_ellipsis.scss
> +  display: inline-block;
inline au lieu d'inline-block

2021-09-17 10:47 UTC, keryanS commented on src/component/link/style/tool/_icon.scss
> +    // overflow: initial;
C'était un test, j'ai oublié de l'enlever

2021-09-24 15:21 UTC, lab9fr requested changes

2021-09-24 15:21 UTC, lab9fr commented on src/component/badge/.package.yml
> +  - scheme
pas de dépendances à scheme, ce sera une option. Le seul composant qui peut avoir cette dépendance, c'est display

2021-09-24 15:21 UTC, lab9fr commented on src/component/badge/example/index.js
> +import '../../../examples/script.js.ejs';
Ce fichier m'a l'air d'un résidu d'une ancienne version outdated, on n'a plus ce fichier normalement
à checker avec le package que tu as pris pour base

2021-09-24 15:21 UTC, lab9fr commented on src/component/badge/style/_module.scss
> +  @include font-weight('bold');
pas de guillements

2021-09-27 15:42 UTC, keryanS commented on src/component/badge/.package.yml
> +  - scheme
Tous les composants ont cette dépendance à scheme. Il vaut peut-être mieux faire cette modif sur la branche scheme dans ce cas

2021-09-27 15:44 UTC, keryanS commented on src/component/badge/example/index.js
> +import '../../../examples/script.js.ejs';
Il est aussi présent dans tag et tile

2021-09-27 17:28 UTC, lab9fr approved these changes

2021-12-07 13:08 UTC, lab9fr requested changes

2021-12-07 13:08 UTC, lab9fr commented on src/component/badge/style/_scheme.scss
> +    @include scheme-element-text-color(default neutral, $legacy);
mettre à jour avec le clean couleur : 
```suggestion
    @include scheme-element-text-color(default neutral, (legacy: $legacy));
```

2021-12-09 15:17 UTC, keryanS commented on src/component/badge/style/_scheme.scss
> +    @include scheme-element-text-color(default neutral, $legacy);
OK + neutral devient grey

2022-01-13 15:38 UTC, lab9fr approved these changes

2022-01-13 15:38 UTC, merged