feat(core): ajout du reset de hr [DS-1882]
GouvernementFR/dsfr pull request #60
Opened 2021-09-14 13:54 UTC by keryanS

2021-09-15 14:58 UTC, lab9fr requested changes

2021-09-15 14:58 UTC, lab9fr commented on src/core/example/spacing/sample/spacing.ejs
> +<hr>
il faudrait plutôt mettre l'exemple dans le reset, non ?

2021-09-15 14:58 UTC, lab9fr commented on src/core/style/reset/scheme/_hr.scss
> +    @include scheme-element-box-shadow-color(g300); // todo: border color
si tu lui mets une hauteur de 1px, j'aurai tendance à dire qu'un background color serait mieux, non ?

2021-09-15 15:12 UTC, keryanS commented on src/core/style/reset/scheme/_hr.scss
> +    @include scheme-element-box-shadow-color(g300); // todo: border color
J'ai pensé à l'arrivé des schemes, me suis dis que c'était une couleur de border donc peut etre pas dispo en background, si ?

2021-09-16 12:56 UTC, keryanS commented on src/core/style/reset/scheme/_hr.scss
> +    @include scheme-element-box-shadow-color(g300); // todo: border color
nécessite une height pour le ox shadow, donc border bottom

2021-09-20 08:47 UTC, lab9fr commented on src/core/style/reset/scheme/_hr.scss
> +    @include scheme-element-box-shadow-color(g300); // todo: border color
Tu peux le mettre dans un after en absolute ?

2021-09-24 15:12 UTC, lab9fr requested changes

2021-09-24 15:12 UTC, lab9fr commented on src/core/style/display/scheme/_hr.scss
> +    @include scheme-element-border-color(g400, true, bottom);
du coup, comme on est en padding, plus forcément besoin d'un before, ça peut redevenir un box shadow si je ne me trompe ?

2021-09-24 15:12 UTC, lab9fr commented on src/core/style/display/module/_hr.scss
> +  @include padding(var(--text-spacing));
je me pose la question de la duplication du code entre hr et fr-hr qui ont exactement le même code du coup, ça créé une classe qui permet de transformer une div en hr.
C'est ce qu'on fait avec les h1 et fr-h1, où on a le même code entre tag natif et classe qui le simule.
Est-ce que ce comportement te convient @jchourdeaux  ?

2021-09-24 15:12 UTC, lab9fr commented on src/core/style/reset/module/_hr.scss
> +    @include padding(var(--text-spacing));
Comme on a un code identique entre tag et classe, il serait préférable de créer une mixin avec ce code pour s'assurer de la similitude des deux.

2021-11-04 11:06 UTC, lab9fr approved these changes

2021-11-04 11:06 UTC, merged