fix: page/pattern dossier vide et npm deploy [DS-1777]
GouvernementFR/dsfr pull request #67
Opened 2021-09-21 10:37 UTC by keryanS

Cache les dossiers vide: scheme, pattern, page, legacy

2021-09-23 16:27 UTC, lab9fr requested changes

2021-09-23 16:27 UTC, lab9fr commented on package.json
> +  "files": [
ajouter .config
retirer yarn.lock

2021-09-27 15:31 UTC, keryanS commented on package.json
> +  "files": [
Il manquait aussi contributing.md

2021-09-27 17:29 UTC, lab9fr approved these changes

2021-09-27 17:29 UTC, merged