🐛 fix(modal): a11y retire la liste dans la zone d'actions [DS-1257]
GouvernementFR/dsfr pull request #720
Opened 2023-07-28 13:32 UTC by zellerbaptiste

2023-08-28 15:25 UTC, keryanS requested changes
- Les boutons doivent rester des `<button>` et non des `<div>`
- retirer les `<div>` vide si non nécéssaire

2023-08-29 08:38 UTC, zellerbaptiste commented
> * Les boutons doivent rester des `<button>` et non des `<div>`
> * retirer les `<div>` vide si non nécéssaire

c'est corrigé

2023-08-29 14:40 UTC, keryanS requested changes

2023-08-29 14:40 UTC, keryanS commented on src/component/button/style/tool/_group.scss
> +  > div {
toujours utile ?

2023-08-29 14:40 UTC, keryanS commented on src/component/button/style/tool/_group.scss
> +  > div {
toujours utile ?

2023-08-30 08:33 UTC, zellerbaptiste commented on src/component/button/style/tool/_group.scss
> +  > div {
non effectivement, je l'ai retiré

2023-09-04 14:04 UTC, keryanS approved these changes

2023-09-08 15:43 UTC, lab9fr approved these changes

2023-11-06 13:56 UTC, merged