🐛 feat(header): correction menu burger [DS-3368]
GouvernementFR/dsfr pull request #722
Opened 2023-07-31 14:53 UTC by zellerbaptiste

- corrige la couleur et les espacements des icônes menu et burger en mobile
- passe le bouton burger en tertiaire avec border

2023-08-28 15:17 UTC, keryanS approved these changes

2023-09-04 12:35 UTC, lab9fr requested changes
Passer le bouton burger en tertiaire avec border

2023-09-04 13:53 UTC, zellerbaptiste commented
> Passer le bouton burger en tertiaire avec border

@lab9fr ce n'est pas l'objet du ticket ?
[3368](https://gouvfr.atlassian.net/browse/DS-3368)

2023-09-08 16:08 UTC, lab9fr commented
@zellerbaptiste 
Ce n'était effectivement pas l'objet du ticket, mais c'est une discussion qui a eu lieu sur Slack et que l'on a conclue avec la mise en place d'un tertiaire avec border pour le menu.
https://gouvfr.slack.com/archives/C04QJ4B78ES/p1693574473712279?thread_ts=1693573496.992289&cid=C04QJ4B78ES

2023-09-11 09:06 UTC, zellerbaptiste commented
> @zellerbaptiste Ce n'était effectivement pas l'objet du ticket, mais c'est une discussion qui a eu lieu sur Slack et que l'on a conclue avec la mise en place d'un tertiaire avec border pour le menu. https://gouvfr.slack.com/archives/C04QJ4B78ES/p1693574473712279?thread_ts=1693573496.992289&cid=C04QJ4B78ES

Ok tu l'as fait 👍 merci

2023-09-26 13:35 UTC, lab9fr approved these changes

2023-10-18 16:18 UTC, keryanS requested changes
Le margin-right(-2v) créé un scroll en mobile -> ajouter overflow hidden sur header-brand

Les boutons de la nav sont plus collé en haut que à gauche -> ajouter 0.25rem de margin top sur header__navbar

2023-10-18 16:25 UTC, keryanS approved these changes

2023-10-20 13:38 UTC, merged