🐛 fix(page-unexpected): inverse les textes principal et de description du model de page [DS-3398]
GouvernementFR/dsfr pull request #723
Opened 2023-07-31 15:00 UTC by zellerbaptiste

2023-08-28 15:15 UTC, keryanS approved these changes

2023-09-01 13:20 UTC, lab9fr requested changes

2023-09-01 13:20 UTC, lab9fr commented on src/page/response/unexpected/i18n/fr.yml
> +  description: Essayez de rafraichir la page ou bien ressayez plus tard.
```suggestion
  description: Essayez de rafraîchir la page ou bien ressayez plus tard.
```

2023-09-01 13:21 UTC, lab9fr approved these changes

2023-11-06 14:13 UTC, merged