✨ feat(select): ajout exemple `<optgroup>` [DS-3374]
GouvernementFR/dsfr pull request #734
Opened 2023-08-21 15:44 UTC by zellerbaptiste

- L'élément HTML `<optgroup>`, utilisé dans un formulaire, permet de créer un groupe d'options parmi lesquelles on peut choisir dans un élément `<select>`.

2023-08-23 09:42 UTC, keryanS requested changes

2023-08-23 09:42 UTC, keryanS commented on src/component/select/template/ejs/select.ejs
Ajouter la doc du param optionGroups en haut

2023-08-24 09:17 UTC, zellerbaptiste commented on src/component/select/template/ejs/select.ejs
c'est fait merci

2023-08-28 15:08 UTC, keryanS approved these changes

2023-09-04 13:21 UTC, lab9fr approved these changes

2023-11-06 15:16 UTC, merged