🐛 fix(select): ajuste la taille et l'emplacement de la flèche [DS-3534]
GouvernementFR/dsfr pull request #736
Opened 2023-08-22 12:27 UTC by zellerbaptiste

2023-08-23 09:34 UTC, keryanS approved these changes

2023-09-04 13:33 UTC, lab9fr requested changes

2023-09-04 13:33 UTC, lab9fr commented on src/component/select/deprecated/example/sample/select.ejs
> +  select.placeholder = select.placeholder || 'Selectionner une option';
```suggestion
  select.placeholder = select.placeholder || 'Sélectionner une option';
```

2023-09-04 13:33 UTC, lab9fr commented on src/component/select/example/sample/select.ejs
> +  select.placeholder = select.placeholder || 'Selectionner une option';
```suggestion
  select.placeholder = select.placeholder || 'Sélectionner une option';
```

2023-09-04 13:33 UTC, lab9fr commented on src/component/select/style/_module.scss
> +  background-size: spacing.space(4v) spacing.space(4v);
```suggestion
  background-size: spacing.space(4v 4v);
```

2023-09-26 13:42 UTC, lab9fr approved these changes

2023-11-06 15:23 UTC, merged