refactor(link): rel noopener & title target blank +  [DS-2509]
GouvernementFR/dsfr pull request #737
Opened 2023-08-23 08:45 UTC by keryanS

Ajout de l'attribut rel="noopener" et title="intitulé - nouvelle fenêtre" à tous les liens en target="_blank"

+ correction tuile avec lien externe

2023-08-28 12:26 UTC, zellerbaptiste approved these changes

2023-09-08 16:24 UTC, lab9fr requested changes
pareil que Baptiste, quid de l'exemple heading, pourquoi ne pas utiliser la même méthode ?

et suggestion qui ferait sens avec notre utilisation du _blank, rajouter rel external. J'ai mis un suggestion commit

2023-09-08 16:24 UTC, lab9fr commented on tool/example/decorator.ejs
> +  attr.rel = 'noopener';
```suggestion
  attr.rel = 'noopener external';
```

2023-09-11 13:26 UTC, keryanS commented on tool/example/decorator.ejs
> +  attr.rel = 'noopener';
ok

2023-10-03 16:01 UTC, lab9fr approved these changes

2023-11-06 16:16 UTC, merged