🐛 fix(radio): met a jour les tokens de couleur [DS-3471]
GouvernementFR/dsfr pull request #760
Opened 2023-09-04 15:23 UTC by zellerbaptiste

- met a jour les token en version cochée des radio et radio riche : 
  - la coche en `$background-active-blue-france`
  - la border en `$border-active-blue-france`

2023-09-05 09:29 UTC, keryanS requested changes
- Passer en active-blue-france sur les version error/succes/infos et cela sur default/sm/rich
- Récréer la branche en 1.10.1 avant pour récuperer le problème de la couleur manquante sur le disabled et éviter de l'écraser.

<img width="1099" alt="Capture d’écran 2023-09-05 à 11 25 29" src="https://github.com/GouvernementFR/dsfr/assets/2979634/08d00c10-3562-48ed-9898-e8e0f10b9ab4">

2023-09-05 10:47 UTC, keryanS commented
Correction apportée au ticket : 
https://gouvfr.atlassian.net/browse/DS-3471
Passer la border en : 
- $border-action-high-blue-france en non coché
- $border-active-blue-france en coché

2023-09-05 14:39 UTC, keryanS requested changes

2023-09-05 14:39 UTC, keryanS commented on src/component/toggle/style/_scheme.scss
>          @include color.text(active blue-france, (legacy:$legacy));
`@include color.text(active blue-france, (legacy:$legacy));` 
inutile sur tous les before et after, à retirer (dans error, succes aussi)

2023-09-05 15:11 UTC, zellerbaptiste commented on src/component/toggle/style/_scheme.scss
>          @include color.text(active blue-france, (legacy:$legacy));
c'est retiré

2023-09-11 12:46 UTC, keryanS requested changes
Autant pour moi la color était nécessaire sur le before pour le "activer/desactiver"
a revert

2023-09-11 15:52 UTC, keryanS approved these changes

2023-10-02 14:42 UTC, lab9fr approved these changes

2023-10-02 15:18 UTC, lab9fr requested changes
sur le radio rich, changer l'ordre des couleurs de manière à ce que la 2e ne soit pas nécéssaire lorsque non checké pour ne pas induire en erreur
grey en premier, coche en second et fond de coche en 3e

2023-11-10 10:55 UTC, lab9fr approved these changes

2023-11-10 13:16 UTC, merged