🐛 fix(navigation): correctifs de style mega-menu [DS-3549, DS-3548]
GouvernementFR/dsfr pull request #785
Opened 2023-09-11 12:56 UTC by zellerbaptiste

- ajoute un `margin-top: -1.25rem` (-20px) sur le `fr-mega-menu__leader`
- passe le texte de description et le lien du `fr-mega-menu__leader` en taille `sm`
- supprime la classe `fr-mb-4v `de la colonne entourant le `fr-mega-menu__leader`
- le texte du bouton de navigation passe en $text-action-high-blue-france à l'ouverture

2023-09-11 17:25 UTC, keryanS requested changes

2023-09-11 17:25 UTC, keryanS commented on src/component/navigation/style/scheme/_default.scss
> +        @include color.text(action-high blue-france, (legacy: $legacy));
Pourquoi changer de token ici ?
Synchro avec le design si nécessaire car ils sont en active aussi

2023-09-11 17:25 UTC, keryanS commented on src/component/navigation/style/module/_mega-menu.scss
> +
- pas besoin du chevron je pense -> juste "p"

+ Nesting de la taille du lien en sm

2023-09-12 12:21 UTC, zellerbaptiste commented on src/component/navigation/style/scheme/_default.scss
> +        @include color.text(action-high blue-france, (legacy: $legacy));
@keryanS c'est le but du ticket : 
https://gouvfr.atlassian.net/browse/DS-3549

2023-09-13 09:56 UTC, zellerbaptiste commented on src/component/navigation/style/module/_mega-menu.scss
> +
c'est corrigé

2023-09-15 14:58 UTC, keryanS requested changes

2023-09-15 14:58 UTC, keryanS commented on src/component/navigation/style/scheme/_default.scss
> +        @include color.text(action-high blue-france, (legacy: $legacy));
ok

2023-09-21 09:24 UTC, zellerbaptiste commented on src/component/navigation/style/module/_mega-menu.scss
> +
ok c'est remplacé

2023-09-21 16:41 UTC, keryanS approved these changes

2023-10-02 13:51 UTC, lab9fr approved these changes

2023-11-09 14:24 UTC, merged