refactor(*): selecteur not combiné [DS-3589]
GouvernementFR/dsfr pull request #786
Opened 2023-09-11 14:18 UTC by keryanS

- Remplacement des selecteurs :not(.selecteurA, .selecteurB) par :not(.selecteurA):not(.selecteurB) dans le js des composants : accordion, navigation, sidemenu, translate, transcription
- La séparation par des virgules est une fonctionnalité assez récente qui n’est pas si bien supportée que ça sur d’anciennes versions de plusieurs navigateurs (firefox, safari, edge…)

2023-09-12 16:09 UTC, zellerbaptiste approved these changes

2023-09-26 08:42 UTC, colinux commented on src/analytics/script/integration/component/transcription/transcription-selector.js
> +  COLLAPSE: `${TRANSCRIPTION} > ${COLLAPSE}, ${TRANSCRIPTION} > *:not(${TRANSCRIPTION}:not(${COLLAPSE}) > ${COLLAPSE}, ${TRANSCRIPTION} > *:not(${TRANSCRIPTION}):not(${COLLAPSE}) > *:not(${TRANSCRIPT
bonjour, je crois qu'il manque une `)` juste avant `:not` sur le premiere sélecteur corrigé : 

`*:not(${TRANSCRIPTION}):not(${COLLAPSE})`
à la place de
`*:not(${TRANSCRIPTION}:not(${COLLAPSE})`

2023-09-26 13:33 UTC, lab9fr requested changes

2023-09-26 13:33 UTC, lab9fr commented on src/analytics/script/integration/component/transcription/transcription-selector.js
> +  COLLAPSE: `${TRANSCRIPTION} > ${COLLAPSE}, ${TRANSCRIPTION} > *:not(${TRANSCRIPTION}:not(${COLLAPSE}) > ${COLLAPSE}, ${TRANSCRIPTION} > *:not(${TRANSCRIPTION}):not(${COLLAPSE}) > *:not(${TRANSCRIPT
```suggestion
  COLLAPSE: `${TRANSCRIPTION} > ${COLLAPSE}, ${TRANSCRIPTION} > *:not(${TRANSCRIPTION}):not(${COLLAPSE}) > ${COLLAPSE}, ${TRANSCRIPTION} > *:not(${TRANSCRIPTION}):not(${COLLAPSE}) > *:not(${TRANSCRIPTION}):not(${COLLAPSE}) > ${COLLAPSE}`,
```

2023-10-02 10:51 UTC, lab9fr approved these changes

2023-11-09 16:06 UTC, merged