🐛 fix(unavailable): corrige la couleur de fond et l'image décorative [DS-3399]
GouvernementFR/dsfr pull request #787
Opened 2023-09-11 15:24 UTC by zellerbaptiste

- change la couleur de fond de page pour du `$background-alt-blue-france`
- remplace l'image décorative par un SVG

2023-09-11 15:48 UTC, keryanS requested changes
Pas besoin des assets jpeg, png, ni même svg puiqu'on inclu un svg inline

2023-09-15 13:40 UTC, keryanS approved these changes

2023-10-03 10:14 UTC, lab9fr requested changes

2023-10-03 10:14 UTC, lab9fr commented on src/page/response/unavailable/standalone/example/index.ejs
> +          <svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" viewBox="0 0 282 320"><g fill="none" fill-rule="evenodd"><path fill="#E3E3FD" d="M36.2053962 315.1c1.2179 0 2.2053.985 2.2053 2.
Mettre le code svg dans un fichier ejs à part pour conserver une page plus simple à lire.

2023-10-03 12:23 UTC, zellerbaptiste commented on src/page/response/unavailable/standalone/example/index.ejs
> +          <svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" viewBox="0 0 282 320"><g fill="none" fill-rule="evenodd"><path fill="#E3E3FD" d="M36.2053962 315.1c1.2179 0 2.2053.985 2.2053 2.
c'est fait

2023-10-03 16:02 UTC, lab9fr approved these changes

2023-10-20 14:37 UTC, keryanS approved these changes

2023-11-09 14:18 UTC, merged