fix(tag): met a jour la page d'exemples
GouvernementFR/dsfr pull request #81
Opened 2021-10-14 16:00 UTC by zellerbaptiste

2021-10-14 20:41 UTC, lab9fr commented on src/component/tag/example/index.ejs
> +<%- sample('Tag seul inactif', './sample/tag-default', {button:true, disabled:true}, true); %>
La traduction de disabled, c'est plutôt désactivé il me semble.
C'est le terme que l'on utilise un peu partout dans les pages d'exemples, si on doit changer, il faudrait le faire partout.
Quelle est la raison de ce changement ?
Et par contre, on devrait peut-être spécifier 'cliquable désactivé'
https://developer.mozilla.org/fr/docs/Web/HTML/Attributes/disabled => là ils parlent de désactivé

2021-11-05 14:31 UTC, jchourdeaux requested changes
@zellerbaptiste @lab9fr , 
pour faire suite à la discussion sur le ticket, gardons le terme "Desactivé" qui est correct (disabled). La nomenclature bougera dans les librairies ui.

2021-11-08 09:35 UTC, zellerbaptiste commented
@jchourdeaux c'est bon cette PR ne comprend plus que le retrait de l'exemple de l'icone à droite.

2021-12-07 13:13 UTC, keryanS approved these changes

2021-12-16 16:19 UTC, closed without merging