docs: Typos et formattage de la doc de contribution
GouvernementFR/dsfr pull request #810
Opened 2023-10-22 16:46 UTC by arnaud

2023-10-26 09:45 UTC, keryanS requested changes

2023-10-26 09:45 UTC, keryanS commented on CONTRIBUTING.md
> +description: description insérée dans le readmed
readmed ?

2023-10-26 21:17 UTC, arnaud commented on CONTRIBUTING.md
> +description: description insérée dans le readmed
```suggestion
description: description insérée dans le readme
```

2023-10-26 21:18 UTC, arnaud commented on CONTRIBUTING.md
> +description: description insérée dans le readmed
^ bien vu, voici un commit pour rétablir la ligne

2023-11-09 09:04 UTC, keryanS approved these changes

2023-11-13 10:43 UTC, merged