🐛 fix(doc): met a jour les liens des pages d'exemple
GouvernementFR/dsfr pull request #822
Opened 2023-11-16 10:52 UTC by zellerbaptiste

Mise à jour des liens vers le site de documentation dans les pages d'exemple.

2023-11-17 15:14 UTC, keryanS approved these changes

2023-11-20 13:44 UTC, merged

2023-11-20 13:50 UTC, lab9fr requested changes

2023-11-20 13:50 UTC, lab9fr commented on README.md
> +[La documentation des favicons](https://www.systeme-de-design.gouv.fr/elements-d-interface/fondamentaux-techniques/icones-de-favoris) détaille la façon de les implémenter dans vos pages.
j'ai une 404 sur cette nouvelle url alors que la précédente fonctionne. étrange.

2023-11-20 13:50 UTC, lab9fr commented on src/core/.package.yml
> +    url: https://www.systeme-de-design.gouv.fr/elements-d-interface/fondamentaux-techniques/icones-de-favoris
même problème