🐛 fix(navigation): corrige bugs de fermeture du composant [DS-3617, DS-3619]
GouvernementFR/dsfr pull request #840
Opened 2023-12-05 15:29 UTC by zellerbaptiste

- corrige un bug de fermeture au clic à l'extérieur du composant sur safari
- corrige un bug de fermeture d'un volet au clic sur un lien ou un bouton à l'intérieur du composant

2023-12-08 16:03 UTC, keryanS requested changes
L'ombre du header disparait à la fermeture.

2023-12-11 08:59 UTC, lab9fr requested changes

2023-12-11 08:59 UTC, lab9fr commented on src/component/navigation/script/navigation/navigation.js
> +    this.listen('click', this._clickHandling.bind(this));
c'est déjà le rôle de listenClick ligne 17

2023-12-11 08:59 UTC, lab9fr commented on src/component/navigation/script/navigation/navigation.js
> +  _clickHandling (e) {
il conserver le nom clickHandler pour correspondre à listenClick

2023-12-11 08:59 UTC, lab9fr commented on src/component/navigation/script/navigation/navigation.js
> +  _clickOut (target) {
pour être plus proche de la nomenclature code, rootClickHandler

2023-12-11 10:09 UTC, zellerbaptiste commented on src/component/navigation/script/navigation/navigation.js
> +  _clickHandling (e) {
La callBack de l'Instance n'est pas  `clickHandler()` mais `handleClick()`

2023-12-11 10:20 UTC, zellerbaptiste commented on src/component/navigation/script/navigation/navigation.js
> +  _clickOut (target) {
`_handleRootClick` pour respecter la nomenclature

2023-12-11 14:20 UTC, zellerbaptiste commented on src/component/navigation/script/navigation/navigation.js
> +    this.listen('click', this._clickHandling.bind(this));
c'est retiré

2023-12-11 14:21 UTC, zellerbaptiste commented on src/component/navigation/script/navigation/navigation.js
> +  _clickHandling (e) {
c'est implémenté dans ce sens

2023-12-11 14:21 UTC, zellerbaptiste commented on src/component/navigation/script/navigation/navigation.js
> +  _clickOut (target) {
c'est implémenté dans ce sens

2023-12-12 16:47 UTC, keryanS commented
Problème d'ombres à l'ouverture et fermeture des menus <img width="1319" alt="image" src="https://github.com/GouvernementFR/dsfr/assets/2979634/0a9edac2-9138-44e6-a799-081dcbd7ebc9">

2023-12-13 10:59 UTC, keryanS commented
> Problème d'ombres à l'ouverture et fermeture des menus <img alt="image" width="1319" src="https://private-user-images.githubusercontent.com/2979634/289939439-0a9edac2-9138-44e6-a799-081dcbd7ebc9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NjUzNjgsIm5iZiI6MTcwMjQ2NTA2OCwicGF0aCI6Ii8yOTc5NjM0LzI4OTkzOTQzOS0wYTllZGFjMi05MTM4LTQ0ZTYtYTc5OS0wODFkY2JkN2ViYzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTNUMTA1NzQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mzg3YWE3NDM4YzBjZDIyODllZTg4MTg0N2Y2ODQzYWU2MjI4NTIxZmU0NmZiYjRkZWM0ZDg4MTM5YmEwOWUxNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vu_f_TmmCOK7zaEij769ZdpHMrMoj4jLzIeyKRPT0j8">

Ce n'est pas lié à cette correction, bug déja présent

2023-12-14 14:27 UTC, keryanS approved these changes

2024-01-16 10:59 UTC, lab9fr approved these changes

2024-01-29 16:45 UTC, merged