✨ feat(card, tile, enlarge-link): ajoute version avec button [DS-3798]
GouvernementFR/dsfr pull request #842
Opened 2023-12-07 16:18 UTC by zellerbaptiste

- Ajout de la possibilité d'utiliser un "button" plutôt qu'un "a" sur la carte et la tuile

2024-01-16 14:26 UTC, keryanS requested changes
- Retirer l'exemple carte avec bouton désactivé
- Retirer l'exemple tuile avec bouton désactivé
- Corriger l'alignement de l'icone en bas à droite des tuiles SM ( right: 1.5rem; bottom: 1.75rem; )

2024-01-16 14:31 UTC, keryanS approved these changes

2024-01-29 18:14 UTC, lab9fr requested changes

2024-01-29 18:14 UTC, lab9fr commented on src/component/card/template/ejs/content.ejs
> +* content.actioneeMarkup (string, optional) : balise de l'actionneur du composant (a, button)
Le terme actionee est utilisé dans les analytics, ça peut prêter à confusion
dans button, on parle simplement de markup
2 pistes de propositions à voir si d'autre : 

- markup
- linkMarkup -> le plus cohérent avec enlarge-link
- interactionMarkup

2024-02-26 15:28 UTC, lab9fr approved these changes

2024-05-29 15:42 UTC, merged