🐛  Fix/header mobile menu links spacing [DS-3683]
GouvernementFR/dsfr pull request #859
Opened 2024-01-08 16:34 UTC by zellerbaptiste

2024-01-08 17:30 UTC, keryanS requested changes
Pas terrible le copier/coller de propriétés, a voir si on peut augmenter le poids du sélecteur, ou remplacer les nest-btn qui posent problème par uniquement les propriétés nécéssaires

2024-01-11 10:51 UTC, zellerbaptiste commented
> Pas terrible le copier/coller de propriétés, a voir si on peut augmenter le poids du sélecteur, ou remplacer les nest-btn qui posent problème par uniquement les propriétés nécéssaires

Suite à notre point je te laisse tester à nouveau @keryanS

2024-01-16 13:55 UTC, keryanS approved these changes

2024-01-31 14:38 UTC, lab9fr approved these changes

2024-01-31 14:43 UTC, merged