refactor: implémentation du js dynamique [DS-1372][DS-1540]
GouvernementFR/dsfr pull request #9
Opened 2021-06-15 19:38 UTC by lab9fr

2021-07-09 14:34 UTC, keryanS commented on src/core/index.js
> +import { Breakpoints } from './scripts/api/register/breakpoints';
Dans un soucis de cohérence, on pourrait mettre l'extention .js partout (ou nul part)

2021-07-09 14:34 UTC, keryanS commented on src/core/scripts/api/engine.js
> +    inspector.debug('START');
Le debug qu'en mode verbose ?

2021-07-09 19:40 UTC, lab9fr commented on src/core/index.js
> +import { Breakpoints } from './scripts/api/register/breakpoints';
oui, c'est l'idée, il faut qu'il soient partout !

2021-07-29 16:52 UTC, keryanS requested changes

2021-07-29 16:52 UTC, keryanS commented on src/core/scripts/api/register/key-codes.js
> -
Il vaut mieux laisser la ligne de fin de fichier non ?

2021-07-29 16:58 UTC, merged