✨ feat(table): tableau v2 [DS-3742]
GouvernementFR/dsfr pull request #911
Opened 2024-03-22 11:03 UTC by zellerbaptiste

2024-05-21 09:40 UTC, keryanS reviewed
J'ai corrigé les erreurs de lint, pense à te mettre en tab indentation : 2 espaces
<img width="1058" alt="image" src="https://github.com/GouvernementFR/dsfr/assets/2979634/3fa99589-2765-49ef-8c0a-60b59db98a19">

Et à ajouter les extensions esLint et styleLint sur VsCode pour voir les erreurs directement :)

2024-05-21 09:41 UTC, keryanS requested changes
Problème de build des exemples au : 
yarn build -h  --config

2024-05-21 10:46 UTC, keryanS requested changes
Sur IE le caption bottom n'a pas de hauteur, l'élement suivant passe par dessus 
<img width="1045" alt="image" src="https://github.com/GouvernementFR/dsfr/assets/2979634/5f63dc1a-aac2-46af-a2a7-6d7202065062">

2024-05-21 10:46 UTC, keryanS commented on src/component/table/style/module/_default.scss
> +@use '../../../../../module/media-query';
```suggestion
@use 'module/media-query';
```

2024-05-21 10:46 UTC, keryanS commented on src/component/table/style/module/_default.scss
> +          font-weight: font-weight(bold);
```suggestion
          @include font-weight(bold);
```

2024-05-21 10:46 UTC, keryanS commented on src/component/table/style/module/_default.scss
> +          z-index: 1;
```suggestion
          @include z-index(over);
```

2024-05-21 10:46 UTC, keryanS commented on src/component/table/style/module/_default.scss
> +              z-index: 4;
Pourquoi 4 ?
Si 2 suffit, `@include z-index(above);`

2024-05-21 10:46 UTC, keryanS commented on src/component/table/style/module/_default.scss
> +              position: absolute;
@include absolute(-0.5v, null, null, 0, 100%, calc(100% + 0.5v));

2024-05-21 10:46 UTC, keryanS commented on src/component/table/style/module/_default.scss
> +          font-size: 0.875rem;
utiliser la mixin @include text-style(sm) ?
pourquoi min-height: 1.2rem ?

2024-05-21 10:46 UTC, keryanS commented on src/component/table/style/module/_default.scss
> +            left: #{space(-5v)};
utiliser plutot spacing.space() à chaque fois
et importer 'module/spacing'

2024-05-21 10:46 UTC, keryanS commented on src/component/table/style/module/_default.scss
> +        &:has(+ *) {
si c'est envisageable, ajouter plutot un margin-left sur #{ns(checkbox-group)} + *
car `:has` n'est pas parfaitement supporté

2024-05-21 10:46 UTC, keryanS commented on src/component/table/style/module/_footer.scss
> +@use '../../../../../module/media-query';
```suggestion
@use 'module/media-query';
```

2024-05-21 10:46 UTC, keryanS commented on src/component/table/style/module/_header.scss
> +@use '../../../../../module/media-query';
```suggestion
@use 'module/media-query';
```

2024-05-21 10:46 UTC, keryanS commented on src/component/table/style/module/_shadow.scss
> +        z-index: 3;
Besoin de niveau 3 ? above ne suffit pas ?

2024-05-21 10:46 UTC, keryanS commented on src/component/table/style/module/_variants.scss
> +      &::before {
```suggestion
      @include before {
```

2024-05-21 10:46 UTC, keryanS commented on src/component/table/template/ejs/table.ejs
table.tbodies

2024-05-21 10:46 UTC, keryanS commented on src/component/table/template/ejs/tbody.ejs
> +        *** tbody.table.tbodies[body][row][col].tag (string, optional): balise de la cellule (th, td)
Utiliser plutot markup, tag prete à confusion

2024-05-21 10:46 UTC, keryanS commented on src/component/table/template/ejs/tbody.ejs
> +                            const colTag = table.tbodies[index][row][col].tag || 'td';
Utiliser plutot markup, tag prete à confusion

2024-05-21 10:46 UTC, keryanS commented on src/component/table/template/ejs/wrapper.ejs
> +
wrapper.header
wrapper.footer

2024-05-21 10:49 UTC, keryanS requested changes
Sur IE la ligne sélectionnée n'a pas les bordures bleu au bon endroit, et la checkbox à 2 focus 
<img width="1265" alt="image" src="https://github.com/GouvernementFR/dsfr/assets/2979634/5230263e-aacd-403d-b423-cc987f161bf1">

2024-05-21 10:49 UTC, keryanS requested changes
Sur IE le caption bottom n'a pas de hauteur, l'élement suivant passe par dessus 
<img width="1045" alt="image" src="https://github.com/GouvernementFR/dsfr/assets/2979634/5f63dc1a-aac2-46af-a2a7-6d7202065062">

2024-05-21 10:52 UTC, keryanS requested changes
Sur IE le caption est trop collé au tableau 
<img width="590" alt="image" src="https://github.com/GouvernementFR/dsfr/assets/2979634/0c82689c-f263-4f89-8b0c-0f075a224f02">

2024-05-21 11:03 UTC, keryanS requested changes
Sur IE
- le caption n'est pas figé, il scroll avec le tableau
- la première colone n'est pas fixée 
<img width="283" alt="image" src="https://github.com/GouvernementFR/dsfr/assets/2979634/c8ee186b-34f1-4064-ba34-91e6620f5f83">

2024-05-21 11:06 UTC, keryanS requested changes
Sur IE, le controle segmenté n'a pas son contour 
<img width="278" alt="image" src="https://github.com/GouvernementFR/dsfr/assets/2979634/f4f4865e-351a-4565-b4ec-8c4dab3cc716">

2024-05-21 11:30 UTC, zellerbaptiste commented on src/component/segmented/template/ejs/segmented.ejs
> +  <% if (segmented.legend !== undefined && !!segmented.legend && segmented.legend.length) { %>
Sur les tableaux le contrôle segmenté est utilisé sans légende : 
<img width="647" alt="Capture d’écran 2024-05-21 à 13 28 59" src="https://github.com/GouvernementFR/dsfr/assets/10864245/8bbacab7-31ba-499f-b274-89cb678eb855">

2024-05-22 08:52 UTC, zellerbaptiste commented
> Sur IE
> 
> * le caption n'est pas figé, il scroll avec le tableau
> * la première colone n'est pas fixée
> 
> <img alt="image" width="283" src="https://private-user-images.githubusercontent.com/2979634/332399700-c8ee186b-34f1-4064-ba34-91e6620f5f83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjgwNTcsIm5iZiI6MTcxNjM2Nzc1NywicGF0aCI6Ii8yOTc5NjM0LzMzMjM5OTcwMC1jOGVlMTg2Yi0zNGYxLTQwNjQtYmEzNC05MWU2NjIwZjVmODMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjJUMDg0OTE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTI1NWFjNDgyYjc4ZGNjY2NmOWU4MzM0MmU5MzMyMzliNmQxMzhhZTEwOGQ0MjliYWQyYWI5MmQ2NTYyNzkxMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.epcvEKJYWNYA61oVvfpnL5wwm079b36C3xPiAfsWgFI">

Sur IE on sera en mode dégradé car le sticky ne fonctionne pas => donc scroll horizontal pour toutes les colonnes + caption

2024-05-22 15:00 UTC, keryanS commented on src/component/segmented/template/ejs/segmented.ejs
> +  <% if (segmented.legend !== undefined && !!segmented.legend && segmented.legend.length) { %>
Cela ne devrait pas, si vraiment le design l'en empêche il faut le mettre en sr-only

2024-05-22 15:37 UTC, zellerbaptiste commented on src/component/table/style/module/_default.scss
> +        &:has(+ *) {
yes ça peut marcher comme ça

2024-05-22 15:56 UTC, zellerbaptiste commented on src/component/segmented/template/ejs/segmented.ejs
> +  <% if (segmented.legend !== undefined && !!segmented.legend && segmented.legend.length) { %>
ok c'est corrigé avec l'option `noLegend`

2024-05-23 09:33 UTC, zellerbaptiste commented on src/component/table/style/module/_default.scss
> +          font-size: 0.875rem;
Ok je suis parti dans ce sens, dis-moi ce que tu en penses.

2024-05-23 12:53 UTC, keryanS requested changes

2024-05-23 12:53 UTC, keryanS commented on src/component/table/i18n/fr.yml
>        selectRow: Selectionner toute la ligne
Sélectionner **toute** la ligne, indique implicitement qu'il est possible de sélectionner qu'une partie de la ligne. J'aurais mis simplement "Sélectionner la ligne"

2024-05-23 12:53 UTC, keryanS commented on src/component/table/style/module/_default.scss
>                background-size: 2px 100%, 2px 100%;
```suggestion
              background-size: spacing.space(0.5v 100%), spacing.space(0.5v 100%);
```

2024-05-23 12:53 UTC, keryanS commented on src/component/table/style/module/_default.scss
> +          width: 0;
```suggestion
          @include size(0);
```

2024-05-23 13:01 UTC, keryanS requested changes
**Les classes `fr-cell__top/bottom/..`. et `fr-col__sm/lg/...` doivent suivre la nomenclature des classes utilitaires à savoir `fr-cell--top` et `fr-col--sm` car il s'agit de modifieurs**

2024-05-24 13:29 UTC, lab9fr requested changes

2024-05-24 13:29 UTC, lab9fr commented on src/component/table/example/sample/table-expandable.ejs
> +<div id="expandable-table" class="<%= prefix %>-table <%= prefix %>-table--bordered <%= prefix %>-table--expandable">
à mettre de côté, dans une autre branche pour que ce ne soit pas dans le code (version brute)

2024-05-24 13:29 UTC, lab9fr commented on src/component/table/script/table/table-selector.js
>    SHADOW_LEFT: api.internals.ns.selector('table__shadow--left'),
est-ce que ces classes shadow sont encore utilisées ?
sinon les retirer

2024-05-24 13:29 UTC, lab9fr commented on src/component/table/script/table/table.js
> +    this.addAscent(TableEmission.COL_SELECT, this.colSelect.bind(this));
à retirer ou commenter, non ? (plus de selection de colonne)

2024-05-24 13:29 UTC, lab9fr commented on src/component/table/script/table/table-selector.js
> +  COL_SELECT: `${api.internals.ns.selector('table')} thead ${api.internals.ns.selector('cell__col--select')} input[type="checkbox"]`
à retirer ou commenter (plus de selection de colonne)

2024-05-24 13:29 UTC, lab9fr commented on src/component/table/main.js
> +api.internals.register(api.table.TableSelector.COL_SELECT, api.table.TableColSelect);
à retirer col select ?

2024-05-24 13:29 UTC, lab9fr commented on src/component/table/script/table/table-col-select.js
> +import api from '../../api.js';
à retirer col select

2024-05-24 13:29 UTC, lab9fr commented on src/component/table/script/table/table-row-select.js
> +import api from '../../api.js';
diviser en 2 niveaux : 
dans form, checkbox, créer une class autour de la checkbox qui émet une emission avec valeur checked et name de la checkbox + event dsfr.
au niveau du row, écouter l'event et changer la valeur en fonction. -> récupérer l'instance enfant checkbox pour checker sa valeur.

2024-05-24 13:38 UTC, zellerbaptiste commented on src/component/button/style/module/_expand.scss
> +  &[aria-expanded='true'] {
est-ce qu'on ajoute une transition dans ce cas là ?

2024-05-24 13:42 UTC, zellerbaptiste commented on src/component/table/script/table/table-selector.js
>    SHADOW_LEFT: api.internals.ns.selector('table__shadow--left'),
Oui elles permettent d'afficher une bordure plus foncée au scroll sur la colonne fixe : 
![Capture d’écran 2024-05-24 à 15 40 51](https://github.com/GouvernementFR/dsfr/assets/10864245/3d5d1ef6-6e87-4fbf-901f-c92e6344b98e)

De plus la version dépréciée les utilise également.

2024-05-24 13:44 UTC, zellerbaptiste commented on src/component/table/script/table/table.js
> +    this.addAscent(TableEmission.COL_SELECT, this.colSelect.bind(this));
La selection de toutes les lignes se base sur cette event via la classe `fr-cell__col--select`

2024-05-24 13:45 UTC, zellerbaptiste commented on src/component/table/main.js
> +api.internals.register(api.table.TableSelector.COL_SELECT, api.table.TableColSelect);
La selection de toutes les lignes utilise cette api

2024-05-24 13:46 UTC, zellerbaptiste commented on src/component/table/script/table/table-col-select.js
> +import api from '../../api.js';
c'est dans ce fichier que l'on gère la selection de toutes les lignes `toggleColSelection`

2024-05-24 13:48 UTC, zellerbaptiste commented on src/component/table/script/table/table.js
> +  colSelect (col) {
c'est l'event qui remonte au clic sur "Sélectionner toutes les lignes"

2024-05-24 13:53 UTC, zellerbaptiste commented on src/component/button/style/module/_sort.scss
> +  &[aria-sorting='asc'] {
est-ce qu'on ajoute une transition dans ce cas là ?

2024-05-24 13:54 UTC, zellerbaptiste commented on src/component/button/style/module/_expand.scss
> +  &[aria-expanded='true'] {
je vais retirer ce bouton de la branche v2 des tableaux car inutile sans la variante de ligne pliée

2024-05-24 14:01 UTC, zellerbaptiste commented on src/component/button/style/module/_expand.scss
> +  &[aria-expanded='true'] {
c'est retiré

2024-05-27 13:45 UTC, zellerbaptiste commented on src/component/button/style/module/_sort.scss
> +  &[aria-sorting='asc'] {
j'ai ajouté le module sass 'animate.rotate'

2024-05-27 14:12 UTC, zellerbaptiste commented on src/component/table/style/module/_default.scss
> +            position: relative;
c'est mis à jour en ce sens

2024-05-27 16:17 UTC, keryanS commented on src/component/button/style/module/_sort.scss
> +  &[aria-sorting='asc'] {
Après reflexion je sais pas si on veut animer la rotation ici, ça risque de faire bizarre. Demander à Alice ce qu'elle en pense

2024-05-29 09:15 UTC, zellerbaptiste commented on src/component/table/script/table/table-selector.js
> +  COL_SELECT: `${api.internals.ns.selector('table')} thead ${api.internals.ns.selector('cell__col--select')} input[type="checkbox"]`
@lab9fr la refacto de la selection de ligne a été poussée

2024-05-29 09:15 UTC, zellerbaptiste commented on src/component/table/script/table/table-selector.js
> +  COL_SELECT: `${api.internals.ns.selector('table')} thead ${api.internals.ns.selector('cell__col--select')} input[type="checkbox"]`
c'est retiré

2024-05-29 09:16 UTC, zellerbaptiste commented on src/component/table/main.js
> +api.internals.register(api.table.TableSelector.COL_SELECT, api.table.TableColSelect);
c'est retiré

2024-05-29 09:16 UTC, zellerbaptiste commented on src/component/table/script/table/table-row-select.js
> +import api from '../../api.js';
@lab9fr la refacto de la selection de ligne a été poussée

2024-05-29 09:16 UTC, zellerbaptiste commented on src/component/table/script/table/table.js
> +  colSelect (col) {
c'est retiré

2024-05-29 09:20 UTC, zellerbaptiste commented on src/component/button/style/module/_sort.scss
> +  &[aria-sorting='asc'] {
vu et validé par Alice

2024-05-29 09:20 UTC, zellerbaptiste commented on src/component/table/script/table/table-col-select.js
> +import api from '../../api.js';
c'est retiré

2024-05-30 17:14 UTC, lab9fr commented on src/component/table/script/table/table-row.js
> +  }
```suggestion
  init () {
    this.isResizing = true;
    if (api.checkbox) {
      this.addAscent(CheckboxEmission.CHANGE, this._handleCheckboxChange.bind(this));
      this.descend(CheckboxEmission.TRIGGER_CHANGE);
    }
  }
```

2024-05-30 17:14 UTC, lab9fr commented on src/component/table/script/table/table-row.js
> +  }
```suggestion
  _handleCheckboxChange (node) {
    if (node.name === 'row-select') {
      this.isSelected = node.checked === true;
    }
  }
```

2024-05-30 17:14 UTC, lab9fr commented on src/component/table/script/table/table-row.js
> +  }
```suggestion

```

2024-05-30 17:14 UTC, lab9fr commented on src/component/table/script/table/table-row.js
> +}
```suggestion
get isSelected () {
return this._isSelected;
}

set isSelected (value) {
   if (this._isSelected === value) return;
   this._isSelected = value;
   this.setAttribute('aria-selected', value);
}
```

2024-05-31 10:25 UTC, zellerbaptiste commented on src/component/checkbox/script/checkbox/checkbox-input.js
> +    this.node.addEventListener('change', this.changing.bind(this));
c'est corrigé

2024-05-31 10:25 UTC, zellerbaptiste commented on src/component/table/script/table/table-row.js
> +  }
c'est corrigé

2024-05-31 10:26 UTC, zellerbaptiste commented on src/component/table/script/table/table-row.js
> +  }
c'est corrigé

2024-05-31 10:26 UTC, zellerbaptiste commented on src/component/table/script/table/table-row.js
> +}
c'est corrigé

2024-05-31 11:44 UTC, lab9fr approved these changes

2024-05-31 13:57 UTC, keryanS approved these changes

2024-05-31 13:59 UTC, merged