✨ feat(navigation): permet l'ajout d'icone sur les liens de navigation
GouvernementFR/dsfr pull request #913
Opened 2024-03-25 16:43 UTC by keryanS

- permet l'ajout d'une icône à gauche sur les nav-btn
- permet l'ajout d'une icône à gauche, par défaut, sur les nav-link ou à droite avec le modifier `fr-lrink--icon-right`

2024-04-22 13:31 UTC, zellerbaptiste approved these changes
Juste une petite typo sur le nom du modifier dans le commentaire de la PR : 
"...le modifier `fr-link--icon-right`"

2024-05-06 10:29 UTC, lab9fr commented
Ajouter des exemples pour visualiser les changements et les valider visuellement : 
- dans les boutons de navigation
- dans les liens de menus simple
- dans les liens de mega-menu
- dans les catégories de mega-menu
pour chacun, ajouter au moins 1 exemple icone à gauche et une à droite, pour que l'on puisse aussi statuer sur lesquelles on autorise et recommande

2024-09-23 13:59 UTC, zellerbaptiste commented
> Ajouter des exemples pour visualiser les changements et les valider visuellement :
> 
> * dans les boutons de navigation
> * dans les liens de menus simple
> * dans les liens de mega-menu
> * dans les catégories de mega-menu
>   pour chacun, ajouter au moins 1 exemple icone à gauche et une à droite, pour que l'on puisse aussi statuer sur lesquelles on autorise et recommande

@keryanS les exemples ont été ajoutés

2024-09-24 08:06 UTC, keryanS commented
Rajouter la possibilité de mettre une icone sur les liens du sidemenu, en passant l'élement actif en background image

2024-10-21 08:32 UTC, lab9fr commented
<img width="388" alt="Screenshot 2024-10-21 at 10 24 44" src="https://github.com/user-attachments/assets/7174d56d-ee4a-4ad3-ba68-5f977895aa29">
petit souci sur la version mobile.
Pas d'exemple pour le moment avec icon sur les boutons, mais c'est quand même possible de placer cette icone.
à voir si on met un cotde pour qu'elle soit en display none ou si on corrige en mode mobile.
Je pose le sujet sur slack avec l'équipe UI.

2024-10-21 08:32 UTC, lab9fr requested changes

2024-10-21 08:47 UTC, lab9fr requested changes

2024-10-21 08:47 UTC, lab9fr commented on src/component/navigation/example/sample/navigation.ejs
> +const getSubLink = (active = false, icon, iconPlace) => {
ça me fait ticker de voir un argument par défaut en premier 
```suggestion
const getSubLink = (active = false, icon = undefined, iconPlace = 'left') => {
```

2024-10-21 08:47 UTC, lab9fr commented on src/component/navigation/example/sample/navigation.ejs
> +const getCategory = (active = false, icon, iconPlace) => {
```suggestion
const getCategory = (active = false, icon = undefined, iconPlace = 'left') => {
```

2024-10-21 08:47 UTC, lab9fr commented on src/component/navigation/style/module/_default.scss
> +      background-size: #{spacing.space(2px calc(100% - 6v))};
idem ici pour le high contrast

2024-10-21 08:47 UTC, lab9fr commented on src/component/navigation/style/module/_default.scss
> +            background-size: #{spacing.space(100% 0.5v)};
j'ai l'impression que la version high contrast a été retirée sans être remise ailleurs.
Est-elle toujours bien fonctionnelle ?

2024-10-25 15:29 UTC, lab9fr commented
En attente de définition des règles d'usage avec Yves

2024-10-29 15:04 UTC, keryanS commented
TODO : Correction mode contrasté

2026-09-09 08:02 UTC, closed without merging