✨ feat(notice): ajout de variations de bandeaux d'information importante [DS-3783, DS-3357]
GouvernementFR/dsfr pull request #917
Opened 2024-04-12 11:11 UTC by keryanS

- ajout des bandeaux d'alertes, des bandeaux météo, et de 2 niveaux génériques (warning et alert)
- mise en situation dans une page

2024-04-12 12:26 UTC, zellerbaptiste commented on src/component/link/template/ejs/link.ejs
> +* link.assess (bool, optional) : si true, ajoute l'attribut permettant le remplissage automatique des informations du fichier à télécharger. Si string, ajoute l'attribut avec la valeur de la string (
Ajoute le type string dans le typage de la donnée : 
```suggestion
* link.assess (bool | string, optional) : si true, ajoute l'attribut permettant le remplissage automatique des informations du fichier à télécharger. Si string, ajoute l'attribut avec la valeur de la string (ex: "bytes" pour les poids en bytes)
```

2024-04-12 13:05 UTC, zellerbaptiste commented on src/component/notice/template/ejs/notice.ejs
> +      <<%= markup %>>
La structure HTML suggérée change mais reste retro-compatible 👍 
`<p class="fr-notice__title">Titre du bandeau d'information</p>`

2024-04-12 13:06 UTC, zellerbaptiste approved these changes

2024-05-06 11:14 UTC, lab9fr requested changes

2024-05-06 11:14 UTC, lab9fr commented on src/component/notice/template/ejs/notice.ejs
> +          <%- include('../../../link/template/ejs/link', {link: {classes: [`${prefix}-notice__link`], isFrLink: false, ...notice.link}}) %>
à discuter l'utilisation du fr-link n'étant pas un fr-link. Peut-être avoir une abstraction intermédiaire dans le corps qui précède fr-link.
En l'état, implémenter un fr-link qui n'en est pas un, c'est problématique.

2024-05-06 11:14 UTC, lab9fr commented on src/component/notice/style/_scheme.scss
> +      @include color.box-shadow(plain error, (legacy:$legacy), top-6-in);
préférer un background-image plutôt qu'un box-shadow

2024-05-21 16:58 UTC, keryanS commented on src/component/notice/style/_scheme.scss
> +      @include color.box-shadow(plain error, (legacy:$legacy), top-6-in);
ok

2024-05-21 16:59 UTC, keryanS commented on src/component/notice/template/ejs/notice.ejs
> +          <%- include('../../../link/template/ejs/link', {link: {classes: [`${prefix}-notice__link`], isFrLink: false, ...notice.link}}) %>
Ajout d'un template action dans core pour gérer le markup, l'état désactivé, et le placement du libellé

2024-05-22 08:47 UTC, lab9fr requested changes

2024-05-22 08:47 UTC, lab9fr commented on src/core/template/ejs/action/action.ejs
> +    markup = 'input';
il manque le type pour le input (button, submit ou reset)

2024-05-30 15:52 UTC, lab9fr approved these changes

2024-05-30 15:52 UTC, lab9fr commented on src/component/notice/.package.yml
> +  - link
```suggestion

```
il y a une dépendance à link ?

2024-05-31 14:04 UTC, merged