✨ feat(analytics): système de régulation des actions
GouvernementFR/dsfr pull request #937
Opened 2024-05-16 18:23 UTC by lab9fr

2024-05-17 08:39 UTC, keryanS approved these changes

2024-05-17 10:22 UTC, zellerbaptiste requested changes
Comme discuté : 
- ajouter cette fonctionnalité sur le `mutate` pour répondre à des besoins de type SPA ou chargement asynchrones,
- ajouter un exemple de cette fonctionnalité sur la page de démonstration des attributs

2024-05-22 12:24 UTC, zellerbaptiste approved these changes

2024-05-27 16:10 UTC, keryanS commented on src/analytics/example/config.ejs
> +    isActionEnabled: true, // ensable action tracking
Si test ok, repasser en non activé par défaut ?

```suggestion
    // isActionEnabled: true, // enable action tracking
```

2024-05-29 16:13 UTC, keryanS requested changes

2024-05-29 16:13 UTC, keryanS approved these changes

2024-05-31 09:26 UTC, merged