🐛 Fix/link card tile enlarge button [DS-3798]
GouvernementFR/dsfr pull request #943
Opened 2024-06-03 13:30 UTC by zellerbaptiste

- ajoute une classe utilitaire `enlarge-button` utilisée sur les cartes et les tuiles de téléchargement pour élargir la zone de clique à tout le composant quand l'element cliquable est un bouton

2024-06-03 14:29 UTC, keryanS requested changes
Utiliser le nouveau template action du core pour inserer le lien, on voit ensemble si tu veux

2024-06-03 14:29 UTC, keryanS commented on src/component/link/template/ejs/link.ejs
> +if (link.assess === true) {
le assess file n'est pas possible en button car pas de href

2024-06-03 14:29 UTC, keryanS commented on src/core/style/action/module/_enlarge.scss
> +  @include enlarge('button');
pas besoin de guillemets je pense

2024-06-03 16:08 UTC, zellerbaptiste commented on src/core/style/action/module/_enlarge.scss
> +  @include enlarge('button');
corrigé

2024-06-03 16:08 UTC, zellerbaptiste commented on src/component/link/template/ejs/link.ejs
> +if (link.assess === true) {
corrigé

2024-06-03 16:08 UTC, zellerbaptiste commented on src/core/style/action/module/_enlarge.scss
> +@mixin enlarge($markup) {
ajouté

2024-06-03 16:09 UTC, zellerbaptiste commented on src/core/style/action/module/_enlarge.scss
>    }
ajouté

2024-06-03 16:09 UTC, zellerbaptiste commented on src/core/style/action/module/_enlarge.scss
> +}
ajouté

2024-06-03 16:09 UTC, zellerbaptiste commented on src/core/style/action/module/_enlarge.scss
> +}
ajouté

2024-06-04 08:34 UTC, keryanS approved these changes

2024-06-04 14:01 UTC, merged