feat(table): ajoute le tableau non scrollable
GouvernementFR/dsfr pull request #947
Opened 2024-06-04 14:29 UTC by zellerbaptiste

2024-06-04 16:41 UTC, lab9fr approved these changes

2024-06-04 16:43 UTC, keryanS requested changes

2024-06-04 16:43 UTC, keryanS commented on src/component/table/style/module/_variants.scss
> +    overflow: hidden;
Il ne faut pas d'overflow hidden en no-scroll si non on risque de cacher le reste du tableau en mobile. Le comportement doit être réduction de la largeur des colonnes au maximum, puis lorsque que plus possible le tableau dépasse de la largeur de la page, un scroll de la page doit alors apparaitre
```suggestion
```

2024-06-04 16:44 UTC, keryanS commented
Sur IE, le contour en haut du tableau n'est déssiné que sur la première colonne.
<img width="816" alt="image" src="https://github.com/GouvernementFR/dsfr/assets/2979634/42487765-add7-493c-a533-771fc8bc5173">

2024-06-05 11:54 UTC, zellerbaptiste commented on src/component/table/style/module/_variants.scss
> +    overflow: hidden;
ok c'est modifié dans ce sens

2024-06-05 11:54 UTC, zellerbaptiste commented
> Sur IE, le contour en haut du tableau n'est déssiné que sur la première colonne. <img alt="image" width="816" src="https://private-user-images.githubusercontent.com/2979634/336537127-42487765-add7-493c-a533-771fc8bc5173.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1ODg3NDcsIm5iZiI6MTcxNzU4ODQ0NywicGF0aCI6Ii8yOTc5NjM0LzMzNjUzNzEyNy00MjQ4Nzc2NS1hZGQ3LTQ5M2MtYTUzMy03NzFmYzhiYzUxNzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDVUMTE1NDA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGE0Zjg2MTdlNzk2NzkzMDk4ZTNlOTcxZWJmYjU3ZjBkYmQ5ZGUzMzI2NmVkMzc1NzA5MWU2NjkyODI5Y2Q4NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.M9vcS3W-7FYEI5b29_dohmgHmAH4R3SzeFJfcITPinc">

c'est corrigé

2024-06-05 13:53 UTC, keryanS approved these changes

2024-06-05 13:56 UTC, merged