🐛 fix(toggle): ajoute les messages erreur et valide sur interrupteur simple
GouvernementFR/dsfr pull request #954
Opened 2024-06-11 10:35 UTC by zellerbaptiste

2024-06-13 09:44 UTC, keryanS requested changes
Les example en erreur et valid sont en double

La bordure d'erreur/succes commence trop tot et fini trop tard :
- Retirer le padding en haut et en bas des toggle (`margin: 1rem 0`)
- Ajouter `margin-bottom: 1rem;` sur les toggle
- modifier `top: 0;` sur toggle:after
- Ajouter `padding-bottom: 1rem;` sur fr-toggle--border-bottom
- Retirer le `top:0` maintenant inutile sur .fr-fieldset .fr-toggle__list li:first-child .fr-toggle label::after
- Retirer le `padding-top: 0;` maintenant inutile sur .fr-fieldset .fr-toggle__list li:first-child .fr-toggle 
- Ajouter `margin-bottom: 0;` sur .fr-fieldset fr-toggle__list li:last-child fr-toggle

2024-06-13 12:39 UTC, zellerbaptiste commented
> Les example en erreur et valid sont en double
> 
> La bordure d'erreur/succes commence trop tot et fini trop tard :
> 
> * Retirer le padding en haut et en bas des toggle (`margin: 1rem 0`)
> * Ajouter `margin-bottom: 1rem;` sur les toggle
> * modifier `top: 0;` sur toggle:after
> * Ajouter `padding-bottom: 1rem;` sur fr-toggle--border-bottom
> * Retirer le `top:0` maintenant inutile sur .fr-fieldset .fr-toggle__list li:first-child .fr-toggle label::after
> * Retirer le `padding-top: 0;` maintenant inutile sur .fr-fieldset .fr-toggle__list li:first-child .fr-toggle
> * Ajouter `margin-bottom: 0;` sur .fr-fieldset fr-toggle__list li:last-child fr-toggle

C'est corrigé

2024-06-13 15:37 UTC, keryanS approved these changes

2024-06-17 09:09 UTC, lab9fr approved these changes

2024-06-17 14:08 UTC, merged